/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 sub_D2C();
void sub_D3C();
void sub_D44();
__int64 (*__fastcall sub_D4C(__int64 (*result)(void)))(void);
__int64 __fastcall sub_D60(void *obj); // idb
__int64 __fastcall sub_D7C(float *a1, __int64 a2, int a3, float a4, float a5);
__int64 __fastcall sub_EC0(float32x2_t *a1, __int64 a2, int a3);
_DWORD *__fastcall sub_10E8(_DWORD *a1, float *a2, float a3, float a4);
__int64 __fastcall sub_1234(float *a1, _OWORD *a2, int a3);
__int64 __fastcall sub_13C8(__int64 *a1);
__int64 __fastcall sub_14B8(__int64 *a1, __int64 a2);
jint JNI_OnLoad(JavaVM *vm, void *reserved);
_QWORD *__fastcall sub_1888(__int64 a1, float a2, __int64 a3, __int64 a4, char a5);
void __fastcall sub_19D4(int a1, int a2, void *ptr);
bool __fastcall sub_19DC(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_19EC(__int64 a1, __int64 a2, __int64 *a3, __int64 a4, unsigned int a5);
__int64 __fastcall sub_1A80(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_1AB0(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall sub_1AB8(__int64 a1, __int64 a2, __int64 *a3);
__int64 __fastcall sub_1AC0(__int64 a1, float a2, float a3, __int64 a4, __int64 a5, int a6, __int64 a7);
void sub_1BB0();
// int __cxa_finalize(void *);
// int __cxa_atexit(void (*lpfunc)(void *), void *obj, void *lpdso_handle);
// __int64 __fastcall __system_property_get(_QWORD, _QWORD); weak
// int atoi(const char *nptr);
// void *malloc(size_t size);
// void free(void *ptr);

//-------------------------------------------------------------------------
// Data declarations

__int128 xmmword_A90 = 0x3F8000003F8000003F80000000000000LL; // weak
_UNKNOWN *off_5C40 = &off_5C40; // weak
char *off_5C48[2] = { "createInternalPathIterator", "(Landroid/graphics/Path;IF)J" }; // weak
char *off_5CF0[2] = { "createInternalPathIterator", "(Landroid/graphics/Path;IF)J" }; // weak
char *off_5D98[2] = { "internalConicToQuadratics", "([FI[FFF)I" }; // weak
__int64 qword_9FD0; // weak
__int64 qword_9FD8; // weak


//----- (0000000000000D2C) ----------------------------------------------------
__int64 sub_D2C()
{
  return __cxa_finalize(&off_5C40);
}
// 5C40: using guessed type _UNKNOWN *off_5C40;

//----- (0000000000000D3C) ----------------------------------------------------
void sub_D3C()
{
  ;
}

//----- (0000000000000D44) ----------------------------------------------------
void sub_D44()
{
  sub_D3C();
}

//----- (0000000000000D4C) ----------------------------------------------------
__int64 (*__fastcall sub_D4C(__int64 (*result)(void)))(void)
{
  if ( result )
    return (__int64 (*)(void))result();
  return result;
}

//----- (0000000000000D60) ----------------------------------------------------
__int64 __fastcall sub_D60(void *obj)
{
  return __cxa_atexit((void (*)(void *))sub_D4C, obj, &off_5C40);
}
// 5C40: using guessed type _UNKNOWN *off_5C40;

//----- (0000000000000D7C) ----------------------------------------------------
__int64 __fastcall sub_D7C(float *a1, __int64 a2, int a3, float a4, float a5)
{
  float v5; // s2
  float v6; // s3
  float v7; // s4
  float v8; // s6
  float v9; // s5
  float v10; // s7
  float v11; // s0
  float v12; // s0
  int v13; // w8
  __int64 result; // x0
  float32x2_t v15; // [xsp+8h] [xbp-38h] BYREF
  float v16; // [xsp+10h] [xbp-30h]
  float v17; // [xsp+14h] [xbp-2Ch]
  float v18; // [xsp+18h] [xbp-28h]
  float v19; // [xsp+1Ch] [xbp-24h]
  float v20; // [xsp+20h] [xbp-20h]
  __int64 v21; // [xsp+28h] [xbp-18h]

  v21 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v6 = *a1;
  v5 = a1[1];
  v8 = a1[2];
  v7 = a1[3];
  v10 = a1[4];
  v9 = a1[5];
  v20 = a4;
  v15.n64_u64[0] = __PAIR64__(LODWORD(v5), LODWORD(v6));
  v16 = v8;
  v17 = v7;
  v18 = v10;
  v19 = v9;
  if ( a5 > 0.0
    && (~LODWORD(a5) & 0x7F800000) != 0
    && (v11 = (float)(a4 + -1.0) / (float)((float)(a4 * 4.0) + 4.0),
        v12 = sqrtf(
                (float)((float)((float)((float)(v6 - (float)(v8 + v8)) + v10) * v11)
                      * (float)((float)((float)(v6 - (float)(v8 + v8)) + v10) * v11))
              + (float)((float)((float)((float)(v5 - (float)(v7 + v7)) + v9) * v11)
                      * (float)((float)((float)(v5 - (float)(v7 + v7)) + v9) * v11))),
        v12 > a5) )
  {
    if ( (float)(v12 * 0.25) <= a5 )
    {
      v13 = 1;
    }
    else if ( (float)(v12 * 0.0625) <= a5 )
    {
      v13 = 2;
    }
    else if ( (float)(v12 * 0.015625) <= a5 )
    {
      v13 = 3;
    }
    else if ( (float)(v12 * 0.0039062) <= a5 )
    {
      v13 = 4;
    }
    else
    {
      v13 = 5;
    }
  }
  else
  {
    v13 = 0;
  }
  result = (unsigned int)(1 << v13);
  if ( (int)result <= a3 )
    return sub_EC0(&v15, a2, v13);
  return result;
}

//----- (0000000000000EC0) ----------------------------------------------------
__int64 __fastcall sub_EC0(float32x2_t *a1, __int64 a2, int a3)
{
  int v5; // w21
  float v6; // s0
  float32x2_t v7; // d3
  float v8; // s1
  float32x2_t v9; // d2
  float32x2_t v10; // d0
  float32x2_t v11; // d4
  float32x2_t v12; // d5
  unsigned __int64 v14; // x8
  unsigned __int64 v15; // d5
  float32x2_t v16; // d1
  bool v17; // zf
  unsigned __int64 v18; // d1
  __int128 v19; // q1
  __int64 result; // x0
  __int64 v21; // x8
  float v22; // s0
  __int64 v23; // x9
  __int64 v28; // x11
  float32x4_t v29; // q1
  float32x4_t *v30; // x10
  float32x4_t v31; // q2
  float32x4_t v32; // q3
  int8x16_t v33; // q0
  int v34; // w10
  __int64 v35; // x8
  float *v36; // x9
  float v37; // t1
  __int64 v39; // x8
  __int64 v40; // x9
  const double *n64_f64; // x11
  unsigned __int64 v42; // x9
  unsigned __int64 v43; // x10
  float64x2_t v44; // q0
  float64x2_t *v45; // x11
  _QWORD *v46; // x10
  unsigned __int64 v47; // x8

  v5 = a3;
  *(float32x2_t *)a2 = (float32x2_t)a1->n64_u64[0];
  if ( a3 < 5 )
    goto LABEL_13;
  v6 = a1[3].n64_f32[0];
  v7.n64_u64[0] = vmul_n_f32(a1[1], v6).n64_u64[0];
  v8 = 1.0 / (float)(v6 + 1.0);
  v9.n64_u64[0] = a1[2].n64_u64[0];
  v10.n64_u64[0] = vmul_n_f32(vadd_f32(v7, (float32x2_t)a1->n64_u64[0]), v8).n64_u64[0];
  v11.n64_u64[0] = vmul_n_f32(
                     vmla_f32(vadd_f32(v9, (float32x2_t)a1->n64_u64[0]), (float32x2_t)0x4000000040000000LL, v7),
                     v8 * 0.5).n64_u64[0];
  v12.n64_u64[0] = vsub_f32(v10, v11).n64_u64[0];
  _ZF = (~v12.n64_u32[0] & 0x7F800000) == 0 || (v12.n64_u32[1] & 0x7F800000) == 2139095040;
  if ( ((v14 = a1[2].n64_u64[0], _ZF) || (v15 = vceqz_f32(v12).n64_u64[0], ((unsigned int)v15 & HIDWORD(v15) & 1) != 0))
    && ((v16.n64_u64[0] = vsub_f32(v11, vmul_n_f32(vadd_f32(v9, v7), v8)).n64_u64[0], (~v16.n64_u32[0] & 0x7F800000) != 0)
      ? (v17 = (v16.n64_u32[1] & 0x7F800000) == 2139095040)
      : (v17 = 1),
        v17 || (v18 = vceqz_f32(v16).n64_u64[0], ((unsigned int)v18 & HIDWORD(v18) & 1) != 0)) )
  {
    *(float32x2_t *)&v19 = v10;
    *(float32x2_t *)(a2 + 24) = v10;
    v5 = 1;
    *(_QWORD *)(a2 + 32) = v14;
    *((float32x2_t *)&v19 + 1) = v10;
    *(_OWORD *)(a2 + 8) = v19;
  }
  else
  {
LABEL_13:
    sub_1234((float *)a1, (_OWORD *)(a2 + 8), a3);
  }
  result = (unsigned int)(1 << v5);
  v21 = (4 * (_DWORD)result) | 2u;
  if ( (int)v21 >= 1 )
  {
    if ( (unsigned int)v21 >= 8 )
    {
      v23 = (4 * (_DWORD)result) & 0x7FFFFFF8;
      __asm { FMOV            V0.4S, #1.0 }
      v28 = (4 * (_DWORD)result) & 0xFFFFFFF8;
      v29 = (float32x4_t)xmmword_A90;
      v30 = (float32x4_t *)(a2 + 16);
      do
      {
        v31 = v30[-1];
        v32 = *v30;
        v30 += 2;
        v28 -= 8;
        v29 = vmulq_f32(v31, v29);
        _Q0 = vmulq_f32(v32, _Q0);
      }
      while ( v28 );
      v33 = vmulq_f32(_Q0, v29);
      v33.n128_u64[0] = vmul_f32((float32x2_t)v33.n128_u64[0], (float32x2_t)vextq_s8(v33, v33, 8u).n128_u64[0]).n64_u64[0];
      v22 = vmuls_lane_f32(v33.n128_f32[0], (float32x2_t)v33.n128_u64[0], 1);
    }
    else
    {
      v22 = 0.0;
      v23 = 0;
    }
    v34 = 2 * result;
    v35 = v21 - v23;
    v36 = (float *)(a2 + 4 * v23);
    do
    {
      v37 = *v36++;
      --v35;
      v22 = v37 * v22;
    }
    while ( v35 );
    if ( v22 != 0.0 && v5 != 31 )
    {
      if ( v34 <= 2 )
        v39 = 2;
      else
        v39 = (unsigned int)v34;
      v40 = v39 - 1;
      if ( (unsigned __int64)(v39 - 1) >= 4
        && ((n64_f64 = a1[1].n64_f64, a2 + 8 >= (unsigned __int64)a1[2].n64_u64)
         || (unsigned __int64)n64_f64 >= a2 + 8 * v39) )
      {
        v43 = v40 & 0xFFFFFFFFFFFFFFFCLL;
        v44 = vld1q_dup_f64(n64_f64);
        v42 = v40 & 0xFFFFFFFFFFFFFFFCLL | 1;
        v45 = (float64x2_t *)(a2 + 24);
        do
        {
          v45[-1] = v44;
          *v45 = v44;
          v45 += 2;
          v43 -= 4LL;
        }
        while ( v43 );
      }
      else
      {
        v42 = 1;
      }
      v46 = (_QWORD *)(a2 + 8 * v42);
      v47 = v39 - v42;
      do
      {
        --v47;
        *v46++ = a1[1].n64_u64[0];
      }
      while ( v47 );
    }
  }
  return result;
}
// FFC: mask 0xFFFFFFF8 is shortened because x8.8 <= 0x7FFFFFFF
// A90: using guessed type __int128 xmmword_A90;

//----- (00000000000010E8) ----------------------------------------------------
_DWORD *__fastcall sub_10E8(_DWORD *a1, float *a2, float a3, float a4)
{
  float v5; // s2
  float v6; // s3
  float v7; // s4
  float v8; // s6
  float v9; // s5
  float v10; // s7
  float v11; // s0
  float v12; // s0
  int v13; // w2
  float32x2_t v15; // [xsp+8h] [xbp-48h] BYREF
  float v16; // [xsp+10h] [xbp-40h]
  float v17; // [xsp+14h] [xbp-3Ch]
  float v18; // [xsp+18h] [xbp-38h]
  float v19; // [xsp+1Ch] [xbp-34h]
  float v20; // [xsp+20h] [xbp-30h]
  __int64 v21; // [xsp+28h] [xbp-28h]

  v21 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v6 = *a2;
  v5 = a2[1];
  v8 = a2[2];
  v7 = a2[3];
  v10 = a2[4];
  v9 = a2[5];
  v20 = a3;
  v15.n64_u64[0] = __PAIR64__(LODWORD(v5), LODWORD(v6));
  v16 = v8;
  v17 = v7;
  v18 = v10;
  v19 = v9;
  if ( a4 > 0.0
    && (~LODWORD(a4) & 0x7F800000) != 0
    && (v11 = (float)(a3 + -1.0) / (float)((float)(a3 * 4.0) + 4.0),
        v12 = sqrtf(
                (float)((float)((float)((float)(v6 - (float)(v8 + v8)) + v10) * v11)
                      * (float)((float)((float)(v6 - (float)(v8 + v8)) + v10) * v11))
              + (float)((float)((float)((float)(v5 - (float)(v7 + v7)) + v9) * v11)
                      * (float)((float)((float)(v5 - (float)(v7 + v7)) + v9) * v11))),
        v12 > a4) )
  {
    if ( (float)(v12 * 0.25) <= a4 )
    {
      v13 = 1;
    }
    else if ( (float)(v12 * 0.0625) <= a4 )
    {
      v13 = 2;
    }
    else if ( (float)(v12 * 0.015625) <= a4 )
    {
      v13 = 3;
    }
    else if ( (float)(v12 * 0.0039062) <= a4 )
    {
      v13 = 4;
    }
    else
    {
      v13 = 5;
    }
  }
  else
  {
    v13 = 0;
  }
  *a1 = sub_EC0(&v15, (__int64)(a1 + 1), v13);
  return a1 + 1;
}

//----- (0000000000001234) ----------------------------------------------------
__int64 __fastcall sub_1234(float *a1, _OWORD *a2, int a3)
{
  float v3; // s0
  float v4; // s2
  float v5; // s17
  float v6; // s16
  float v7; // s6
  float v8; // s18
  float v9; // s4
  float v10; // s1
  float v11; // s5
  float v12; // s7
  float v13; // s2
  float v14; // s3
  float v15; // s5
  float v16; // s4
  float v17; // s5
  float v18; // s2
  unsigned int v19; // w19
  __int64 v20; // x0
  __int64 result; // x0
  __int128 v22; // q0
  __int64 v23; // [xsp+0h] [xbp-60h] BYREF
  float v24; // [xsp+8h] [xbp-58h]
  float v25; // [xsp+Ch] [xbp-54h]
  float v26; // [xsp+10h] [xbp-50h]
  float v27; // [xsp+14h] [xbp-4Ch]
  float v28; // [xsp+18h] [xbp-48h]
  float v29; // [xsp+1Ch] [xbp-44h] BYREF
  float v30; // [xsp+20h] [xbp-40h]
  float v31; // [xsp+24h] [xbp-3Ch]
  float v32; // [xsp+28h] [xbp-38h]
  __int64 v33; // [xsp+2Ch] [xbp-34h]
  float v34; // [xsp+34h] [xbp-2Ch]
  __int64 v35; // [xsp+38h] [xbp-28h]

  v35 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  if ( a3 )
  {
    v3 = a1[5];
    v4 = a1[6];
    v5 = a1[4];
    v6 = a1[3];
    v7 = a1[2] * v4;
    v8 = v6 * v4;
    v23 = *(_QWORD *)a1;
    v9 = 1.0 / (float)(v4 + 1.0);
    v11 = *a1;
    v10 = a1[1];
    v33 = *((_QWORD *)a1 + 2);
    v12 = sqrtf((float)(v4 * 0.5) + 0.5);
    v13 = (float)((float)(v3 + v10) + (float)((float)(v6 * v4) * 2.0)) * (float)(v9 * 0.5);
    v14 = (float)(v8 + v10) * v9;
    v26 = (float)((float)(v5 + v11) + (float)(v7 * 2.0)) * (float)(v9 * 0.5);
    v27 = v13;
    v24 = (float)(v7 + v11) * v9;
    v25 = v14;
    v15 = (float)(v5 + v7) * v9;
    v16 = (float)(v3 + v8) * v9;
    v30 = v13;
    v31 = v15;
    v32 = v16;
    v34 = v12;
    v28 = v12;
    v29 = v26;
    if ( (float)((float)(v3 - v6) * (float)(v10 - v6)) <= 0.0 )
    {
      if ( (float)((float)(v3 - v13) * (float)(v10 - v13)) > 0.0 )
      {
        v17 = v13 - v10;
        v18 = v13 - v3;
        if ( v17 < 0.0 )
          v17 = -v17;
        if ( v18 < 0.0 )
          v18 = -v18;
        if ( v17 >= v18 )
          v13 = v3;
        else
          v13 = v10;
        v30 = v13;
        v27 = v13;
      }
      if ( (float)((float)(v13 - v14) * (float)(v10 - v14)) > 0.0 )
        v25 = v10;
      if ( (float)((float)(v3 - v16) * (float)(v13 - v16)) > 0.0 )
        v32 = v3;
    }
    v19 = a3 - 1;
    v20 = sub_1234(&v23, a2, (unsigned int)(a3 - 1));
    return sub_1234(&v29, v20, v19);
  }
  else
  {
    v22 = *(_OWORD *)(a1 + 2);
    result = (__int64)(a2 + 1);
    *a2 = v22;
  }
  return result;
}

//----- (00000000000013C8) ----------------------------------------------------
__int64 __fastcall sub_13C8(__int64 *a1)
{
  int v2; // w8
  float *v3; // x23
  _BYTE *v4; // x25
  int v5; // w22
  unsigned int v6; // w20
  __int64 v7; // x24
  _BYTE *v8; // x9
  float v9; // t1

  if ( *((_BYTE *)a1 + 33) )
  {
    v2 = *((_DWORD *)a1 + 7);
    if ( v2 < 1 )
    {
      return 0;
    }
    else
    {
      v4 = (_BYTE *)a1[1];
      v3 = (float *)a1[2];
      v5 = 0;
      v6 = 0;
      v7 = *a1;
      do
      {
        if ( *((_BYTE *)a1 + 32) )
          v8 = v4 - 1;
        else
          v8 = v4;
        if ( *((_BYTE *)a1 + 32) )
          --v4;
        else
          ++v4;
        switch ( *v8 )
        {
          case 0:
          case 1:
            v7 += 8;
            goto LABEL_5;
          case 2:
            v7 += 16;
            goto LABEL_5;
          case 3:
            v9 = *v3++;
            sub_10E8((_DWORD *)a1 + 10, (float *)(v7 - 8), v9, *((float *)a1 + 9));
            v7 += 16;
            v6 += *((_DWORD *)a1 + 10);
            v2 = *((_DWORD *)a1 + 7);
            break;
          case 4:
            v7 += 24;
            goto LABEL_5;
          case 5:
          case 6:
LABEL_5:
            ++v6;
            break;
          default:
            break;
        }
        ++v5;
      }
      while ( v5 < v2 );
    }
  }
  else
  {
    return *((unsigned int *)a1 + 7);
  }
  return v6;
}

//----- (00000000000014B8) ----------------------------------------------------
__int64 __fastcall sub_14B8(__int64 *a1, __int64 a2)
{
  int v2; // w8
  int v5; // w10
  _DWORD *v6; // x21
  int v7; // w9
  int v8; // w9
  _QWORD *v9; // x10
  __int64 result; // x0
  __int64 v11; // x9
  float *v12; // x8
  int v13; // w10
  float v14; // s0
  __int64 v15; // x9
  float v16; // s1
  __int64 v17; // x8
  char *v18; // x8
  char *v19; // x10

  v2 = *((_DWORD *)a1 + 6);
  if ( v2 < 1 )
    return 6;
  v6 = a1 + 5;
  v5 = *((_DWORD *)a1 + 10);
  v7 = *((_DWORD *)a1 + 141);
  if ( v7 == v5 )
  {
    while ( 1 )
    {
      v8 = *((unsigned __int8 *)a1 + 32);
      v9 = (_QWORD *)a1[1];
      *((_DWORD *)a1 + 6) = v2 - 1;
      result = *((unsigned __int8 *)v9 - (v8 != 0));
      v11 = v8 ? (__int64)v9 - 1 : (__int64)v9 + 1;
      a1[1] = v11;
      if ( (_DWORD)result != 3 )
        break;
      *(_QWORD *)a2 = *(_QWORD *)(*a1 - 8);
      *(_QWORD *)(a2 + 8) = *(_QWORD *)*a1;
      *(_QWORD *)(a2 + 16) = *(_QWORD *)(*a1 + 8);
      v12 = (float *)a1[2];
      v13 = *((unsigned __int8 *)a1 + 33);
      v14 = *v12;
      v15 = *a1 + 16;
      *(float *)(a2 + 24) = *v12;
      v16 = *v12;
      a1[2] = (__int64)(v12 + 1);
      *a1 = v15;
      *(float *)(a2 + 28) = v16;
      if ( v13 != 1 )
        return 3;
      sub_10E8(v6, (float *)a2, v14, *((float *)a1 + 9));
      v5 = *((_DWORD *)a1 + 10);
      *((_DWORD *)a1 + 141) = 0;
      if ( v5 )
      {
        v7 = 0;
        goto LABEL_20;
      }
      v2 = *((_DWORD *)a1 + 6);
    }
    switch ( (int)result )
    {
      case 0:
        result = 0;
        *(_QWORD *)a2 = *(_QWORD *)*a1;
        goto LABEL_15;
      case 1:
        result = 1;
        *(_QWORD *)a2 = *(_QWORD *)(*a1 - 8);
        *(_QWORD *)(a2 + 8) = *(_QWORD *)*a1;
LABEL_15:
        v17 = *a1 + 8;
        goto LABEL_18;
      case 2:
        result = 2;
        *(_QWORD *)a2 = *(_QWORD *)(*a1 - 8);
        *(_QWORD *)(a2 + 8) = *(_QWORD *)*a1;
        *(_QWORD *)(a2 + 16) = *(_QWORD *)(*a1 + 8);
        v17 = *a1 + 16;
        goto LABEL_18;
      case 4:
        result = 4;
        *(_QWORD *)a2 = *(_QWORD *)(*a1 - 8);
        *(_QWORD *)(a2 + 8) = *(_QWORD *)*a1;
        *(_QWORD *)(a2 + 16) = *(_QWORD *)(*a1 + 8);
        *(_QWORD *)(a2 + 24) = *(_QWORD *)(*a1 + 16);
        v17 = *a1 + 24;
LABEL_18:
        *a1 = v17;
        break;
      default:
        return result;
    }
  }
  else
  {
LABEL_20:
    v18 = (char *)a1 + 44;
    if ( v5 <= 0 )
      v18 = 0;
    result = 2;
    v19 = &v18[16 * v7];
    *(_QWORD *)a2 = *(_QWORD *)v19;
    *(_QWORD *)(a2 + 8) = *(_QWORD *)&v18[16 * v7 + 8];
    *(_QWORD *)(a2 + 16) = *((_QWORD *)v19 + 2);
    ++*((_DWORD *)a1 + 141);
  }
  return result;
}

//----- (00000000000016C8) ----------------------------------------------------
jint JNI_OnLoad(JavaVM *vm, void *reserved)
{
  jint result; // w0
  __int64 v3; // x0
  __int64 v4; // x0
  __int64 v5; // x19
  int v6; // w0
  __int64 v7; // x0
  char **v8; // x2
  __int64 v9; // x0
  __int64 v10; // x19
  __int64 v11; // [xsp+8h] [xbp-98h] BYREF
  char nptr[16]; // [xsp+10h] [xbp-90h] BYREF
  __int128 v13; // [xsp+20h] [xbp-80h]
  __int128 v14; // [xsp+30h] [xbp-70h]
  __int128 v15; // [xsp+40h] [xbp-60h]
  _DWORD v16[7]; // [xsp+50h] [xbp-50h] BYREF
  __int64 v17; // [xsp+78h] [xbp-28h]

  v17 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  if ( (*vm)->GetEnv(vm, (void **)&v11, 65542) )
    return -1;
  v3 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)v11 + 48LL))(v11, "android/graphics/Path");
  qword_9FD0 = v3;
  if ( !v3 )
    return -1;
  qword_9FD8 = (*(__int64 (__fastcall **)(__int64, __int64, const char *, const char *))(*(_QWORD *)v11 + 752LL))(
                 v11,
                 v3,
                 "mNativePath",
                 "J");
  if ( !qword_9FD8 )
    return -1;
  v4 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)v11 + 48LL))(
         v11,
         "androidx/graphics/path/PathIteratorPreApi34Impl");
  if ( !v4 )
    return -1;
  v5 = v4;
  v15 = 0u;
  memset(v16, 0, sizeof(v16));
  v13 = 0u;
  v14 = 0u;
  *(_OWORD *)nptr = 0u;
  if ( (int)__system_property_get("ro.build.version.sdk", nptr) >= 1
    && (v6 = atoi(nptr), v6 > 0)
    && (unsigned int)v6 < 0x1A )
  {
    v7 = v11;
    v8 = off_5CF0;
  }
  else
  {
    v7 = v11;
    v8 = off_5C48;
  }
  result = (*(__int64 (__fastcall **)(__int64, __int64, char **, __int64))(*(_QWORD *)v7 + 1720LL))(v7, v5, v8, 7);
  if ( !result )
  {
    (*(void (__fastcall **)(__int64, __int64))(*(_QWORD *)v11 + 184LL))(v11, v5);
    v9 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)v11 + 48LL))(
           v11,
           "androidx/graphics/path/ConicConverter");
    if ( v9 )
    {
      v10 = v9;
      result = (*(__int64 (__fastcall **)(__int64, __int64, char **, __int64))(*(_QWORD *)v11 + 1720LL))(
                 v11,
                 v9,
                 off_5D98,
                 1);
      if ( !result )
      {
        (*(void (__fastcall **)(__int64, __int64))(*(_QWORD *)v11 + 184LL))(v11, v10);
        return 65542;
      }
      return result;
    }
    return -1;
  }
  return result;
}
// 1C00: using guessed type __int64 __fastcall __system_property_get(_QWORD, _QWORD);
// 5C48: using guessed type char *off_5C48[2];
// 5CF0: using guessed type char *off_5CF0[2];
// 5D98: using guessed type char *off_5D98[2];
// 9FD0: using guessed type __int64 qword_9FD0;
// 9FD8: using guessed type __int64 qword_9FD8;

//----- (0000000000001888) ----------------------------------------------------
_QWORD *__fastcall sub_1888(__int64 a1, float a2, __int64 a3, __int64 a4, char a5)
{
  _QWORD *v7; // x20
  int v8; // w0
  char v9; // w22
  __int64 *v10; // x8
  __int64 *v11; // x9
  __int64 *v12; // x10
  int *v13; // x11
  __int64 v14; // x20
  __int64 v15; // x23
  __int64 v16; // x24
  int v17; // w25
  _QWORD *result; // x0
  _OWORD v19[6]; // [xsp+0h] [xbp-C0h] BYREF
  __int64 v20; // [xsp+68h] [xbp-58h]

  v20 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v7 = (_QWORD *)(*(__int64 (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 808LL))(a1, a4, qword_9FD8);
  memset(v19, 0, 92);
  if ( (int)__system_property_get("ro.build.version.sdk", v19) >= 1
    && (v8 = atoi((const char *)v19), v8 > 0)
    && (unsigned int)v8 < 0x1E )
  {
    if ( (unsigned int)v8 < 0x1A )
    {
      v10 = (__int64 *)(*v7 + 32LL);
      v11 = (__int64 *)(*v7 + 40LL);
      v12 = (__int64 *)(*v7 + 64LL);
      v13 = (int *)(*v7 + 48LL);
    }
    else
    {
      v10 = (__int64 *)(*v7 + 24LL);
      v11 = (__int64 *)(*v7 + 32LL);
      v12 = (__int64 *)(*v7 + 56LL);
      v13 = (int *)(*v7 + 40LL);
    }
    v9 = 1;
  }
  else
  {
    v9 = 0;
    v10 = (__int64 *)(*v7 + 24LL);
    v11 = (__int64 *)(*v7 + 40LL);
    v12 = (__int64 *)(*v7 + 56LL);
    v13 = (int *)(*v7 + 52LL);
  }
  v14 = *v10;
  v15 = *v11;
  v16 = *v12;
  v17 = *v13;
  result = malloc(0x238u);
  *result = v14;
  result[1] = v15;
  result[2] = v16;
  *((_DWORD *)result + 6) = v17;
  *((_DWORD *)result + 7) = v17;
  *((_BYTE *)result + 32) = v9;
  *((_BYTE *)result + 33) = a5;
  *((float *)result + 9) = a2;
  *((_DWORD *)result + 10) = 0;
  *((_DWORD *)result + 141) = 0;
  return result;
}
// 1C00: using guessed type __int64 __fastcall __system_property_get(_QWORD, _QWORD);
// 9FD8: using guessed type __int64 qword_9FD8;

//----- (00000000000019D4) ----------------------------------------------------
void __fastcall sub_19D4(int a1, int a2, void *ptr)
{
  free(ptr);
}

//----- (00000000000019DC) ----------------------------------------------------
bool __fastcall sub_19DC(__int64 a1, __int64 a2, __int64 a3)
{
  return *(_DWORD *)(a3 + 24) > 0;
}

//----- (00000000000019EC) ----------------------------------------------------
__int64 __fastcall sub_19EC(__int64 a1, __int64 a2, __int64 *a3, __int64 a4, unsigned int a5)
{
  unsigned __int8 v8; // w21
  _BYTE v10[32]; // [xsp+8h] [xbp-58h] BYREF
  __int64 v11; // [xsp+28h] [xbp-38h]

  v11 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v8 = sub_14B8(a3, (__int64)v10);
  if ( (unsigned __int8)(v8 - 7) <= 0xFDu )
    (*(void (__fastcall **)(__int64, __int64, _QWORD, __int64, _BYTE *))(*(_QWORD *)a1 + 1704LL))(a1, a4, a5, 8, v10);
  return v8;
}

//----- (0000000000001A80) ----------------------------------------------------
__int64 __fastcall sub_1A80(__int64 a1, __int64 a2, __int64 a3)
{
  if ( *(int *)(a3 + 24) < 1 )
    return 6;
  else
    return *(unsigned __int8 *)(*(_QWORD *)(a3 + 8) - (*(_BYTE *)(a3 + 32) != 0));
}

//----- (0000000000001AB0) ----------------------------------------------------
__int64 __fastcall sub_1AB0(__int64 a1, __int64 a2, __int64 a3)
{
  return *(unsigned int *)(a3 + 28);
}

//----- (0000000000001AB8) ----------------------------------------------------
__int64 __fastcall sub_1AB8(__int64 a1, __int64 a2, __int64 *a3)
{
  return sub_13C8(a3);
}

//----- (0000000000001AC0) ----------------------------------------------------
__int64 __fastcall sub_1AC0(__int64 a1, float a2, float a3, __int64 a4, __int64 a5, int a6, __int64 a7)
{
  __int64 v13; // x23
  __int64 v14; // x24
  int v15; // w0
  unsigned int v16; // w21

  v13 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)a1 + 1512LL))(a1, a5, 0);
  v14 = (*(__int64 (__fastcall **)(__int64, __int64, _QWORD))(*(_QWORD *)a1 + 1512LL))(a1, a7, 0);
  v15 = (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)a1 + 1368LL))(a1, a7);
  v16 = sub_D7C((float *)(v13 + 4LL * a6), v14, v15, a2, a3);
  (*(void (__fastcall **)(__int64, __int64, __int64, __int64))(*(_QWORD *)a1 + 1576LL))(a1, a5, v13, 2);
  (*(void (__fastcall **)(__int64, __int64, __int64, _QWORD))(*(_QWORD *)a1 + 1576LL))(a1, a7, v14, 0);
  return v16;
}

//----- (0000000000001BB0) ----------------------------------------------------
void sub_1BB0()
{
  JUMPOUT(0);
}
// 1BC0: control flows out of bounds to 0

// nfuncs=35 queued=21 decompiled=21 lumina nreq=0 worse=0 better=0
// ALL OK, 21 function(s) have been successfully decompiled
