/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'libdigitalitem_image_decoder.so'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

union $955F1759725876F7F898C71A8A4DCDA3;
union $AEC512E533A23DF0E4E7770B7D3B7341;

/* 1 */
struct Elf64_Sym
{
  unsigned __int32 st_name __offset(OFF64,0x48BC);
  unsigned __int8 st_info;
  unsigned __int8 st_other;
  unsigned __int16 st_shndx;
  unsigned __int64 st_value __off;
  unsigned __int64 st_size;
};

/* 2 */
struct Elf64_Rela
{
  unsigned __int64 r_offset;
  unsigned __int64 r_info;
  __int64 r_addend;
};

/* 3 */
struct Elf64_Dyn
{
  unsigned __int64 d_tag;
  unsigned __int64 d_un;
};

/* 4 */
struct Elf64_Verneed
{
  unsigned __int16 vn_version;
  unsigned __int16 vn_cnt;
  unsigned __int32 vn_file __offset(OFF64,0x48BC);
  unsigned __int32 vn_aux;
  unsigned __int32 vn_next;
};

/* 5 */
struct Elf64_Vernaux
{
  unsigned __int32 vna_hash;
  unsigned __int16 vna_flags;
  unsigned __int16 vna_other;
  unsigned __int32 vna_name __offset(OFF64,0x48BC);
  unsigned __int32 vna_next;
};

/* 6 */
struct type_info;

/* 7 */
struct __class_type_info;

/* 9 */
typedef unsigned __int64 __dev_t;

/* 12 */
typedef unsigned __int64 __kernel_ulong_t;

/* 11 */
typedef __kernel_ulong_t __kernel_ino_t;

/* 10 */
typedef __kernel_ino_t __ino_t;

/* 15 */
typedef unsigned int __uint32_t;

/* 14 */
typedef __uint32_t uint32_t;

/* 13 */
typedef uint32_t __nlink_t;

/* 17 */
typedef unsigned int __kernel_mode_t;

/* 16 */
typedef __kernel_mode_t __mode_t;

/* 19 */
typedef unsigned int __kernel_uid32_t;

/* 18 */
typedef __kernel_uid32_t __uid_t;

/* 21 */
typedef unsigned int __kernel_gid32_t;

/* 20 */
typedef __kernel_gid32_t __gid_t;

/* 22 */
typedef __int64 __off_t;

/* 23 */
typedef __int64 __blksize_t;

/* 24 */
typedef __int64 __blkcnt_t;

/* 25 */
struct timespec;

/* 26 */
typedef __int64 __syscall_slong_t;

/* 8 */
struct stat
{
  __dev_t st_dev;
  __ino_t st_ino;
  __nlink_t st_nlink;
  __mode_t st_mode;
  __uid_t st_uid;
  __gid_t st_gid;
  int __pad0;
  __dev_t st_rdev;
  __off_t st_size;
  __blksize_t st_blksize;
  __blkcnt_t st_blocks;
  struct timespec st_atim;
  struct timespec st_mtim;
  struct timespec st_ctim;
  __syscall_slong_t __unused[3];
};

/* 27 */
typedef unsigned __int64 size_t;

/* 28 */
struct std::type_info;

/* 29 */
struct std::bad_cast;

/* 30 */
struct std::bad_typeid;

/* 31 */
struct std::exception;

/* 32 */
struct std::bad_exception;

/* 33 */
struct std::bad_alloc;

/* 34 */
struct std::bad_array_new_length;

/* 35 */
struct std::nothrow_t;

/* 36 */
union __attribute__((aligned(8))) __n64
{
  unsigned __int64 n64_u64[1];
  unsigned __int32 n64_u32[2];
  unsigned __int16 n64_u16[4];
  unsigned __int8 n64_u8[8];
  __int64 n64_i64[1];
  __int32 n64_i32[2];
  __int16 n64_i16[4];
  __int8 n64_i8[8];
  float n64_f32[2];
  double n64_f64[1];
};

/* 37 */
union __attribute__((aligned(8))) __n128
{
  unsigned __int64 n128_u64[2];
  unsigned __int32 n128_u32[4];
  unsigned __int16 n128_u16[8];
  unsigned __int8 n128_u8[16];
  __int64 n128_i64[2];
  __int32 n128_i32[4];
  __int16 n128_i16[8];
  __int8 n128_i8[16];
  float n128_f32[4];
  double n128_f64[2];
};

/* 38 */
typedef __n64 int8x8_t;

/* 39 */
typedef __n64 uint8x8_t;

/* 40 */
typedef __n64 int16x4_t;

/* 41 */
typedef __n64 int32x2_t;

/* 42 */
typedef __n64 uint16x4_t;

/* 43 */
typedef __n64 uint32x2_t;

/* 44 */
typedef __n128 int8x16_t;

/* 45 */
typedef __n128 int16x8_t;

/* 46 */
typedef __n128 int32x4_t;

/* 47 */
typedef __n128 int64x2_t;

/* 48 */
typedef __n128 uint8x16_t;

/* 49 */
typedef __n128 uint16x8_t;

/* 50 */
typedef __n128 uint32x4_t;

/* 51 */
typedef __n128 uint64x2_t;

/* 52 */
typedef __n64 poly8x8_t;

/* 53 */
typedef __n64 poly16x4_t;

/* 54 */
typedef __n128 poly16x8_t;

/* 55 */
typedef __n128 poly8x16_t;

/* 56 */
typedef __n64 float16x4_t;

/* 57 */
typedef __n64 float32x2_t;

/* 58 */
typedef __n128 float16x8_t;

/* 59 */
typedef __n128 float32x4_t;

/* 60 */
typedef __n128 float64x2_t;

/* 61 */
typedef __n128 poly128_t;

/* 62 */
typedef int16x4_t int16x2_t;

/* 63 */
typedef uint16x4_t uint16x2_t;

/* 64 */
typedef float16x4_t float16x2_t;

/* 65 */
struct __va_list_tag
{
  void *__stack;
  void *__gr_top;
  void *__vr_top;
  int __gr_offs;
  int __vr_offs;
};

/* 66 */
typedef __va_list_tag gcc_va_list[1];

/* 67 */
struct int8x16x2_t
{
  int8x16_t val[2];
};

/* 68 */
struct int8x16x4_t
{
  int8x16_t val[4];
};

/* 69 */
struct int8x8x2_t
{
  int8x8_t val[2];
};

/* 70 */
struct int8x8x4_t
{
  int8x8_t val[4];
};

/* 71 */
struct int8x16x3_t
{
  int8x16_t val[3];
};

/* 72 */
struct int8x8x3_t
{
  int8x8_t val[3];
};

/* 73 */
struct int16x8x4_t
{
  int16x8_t val[4];
};

/* 74 */
typedef union $955F1759725876F7F898C71A8A4DCDA3 pthread_mutex_t;

/* 78 */
struct __pthread_internal_list
{
  struct __pthread_internal_list *__prev;
  struct __pthread_internal_list *__next;
};

/* 77 */
typedef struct __pthread_internal_list __pthread_list_t;

/* 76 */
struct $955F1759725876F7F898C71A8A4DCDA3::__pthread_mutex_s
{
  int __lock;
  unsigned int __count;
  int __owner;
  unsigned int __nusers;
  int __kind;
  int __spins;
  __pthread_list_t __list;
};

/* 75 */
union $955F1759725876F7F898C71A8A4DCDA3
{
  struct $955F1759725876F7F898C71A8A4DCDA3::__pthread_mutex_s __data;
  char __size[40];
  __int64 __align;
};

/* 79 */
typedef union $AEC512E533A23DF0E4E7770B7D3B7341 pthread_rwlock_t;

/* 81 */
struct $AEC512E533A23DF0E4E7770B7D3B7341::$D894E3326F078364D3B6CBCD0A540AF0
{
  int __lock;
  unsigned int __nr_readers;
  unsigned int __readers_wakeup;
  unsigned int __writer_wakeup;
  unsigned int __nr_readers_queued;
  unsigned int __nr_writers_queued;
  int __writer;
  int __shared;
  unsigned __int64 __pad1;
  unsigned __int64 __pad2;
  unsigned int __flags;
};

/* 80 */
union $AEC512E533A23DF0E4E7770B7D3B7341
{
  struct $AEC512E533A23DF0E4E7770B7D3B7341::$D894E3326F078364D3B6CBCD0A540AF0 __data;
  char __size[56];
  __int64 __align;
};

