/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 sub_D30();
void sub_D40();
void sub_D48();
__int64 (*__fastcall sub_D50(__int64 (*result)(void)))(void);
__int64 __fastcall sub_D64(void *obj); // idb
__int64 __fastcall ThrowIoException(_JNIEnv *a1, const char *a2); // idb
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeTruncateFile(__int64 a1, int a2, datastore *this);
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeCreateSharedCounter(__int64 a1, int a2, void **this);
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeGetCounterValue(__int64 a1, __int64 a2, unsigned int *a3);
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeIncrementAndGetCounterValue(__int64 a1, __int64 a2, atomic_uint *a3);
__int64 __fastcall datastore::TruncateFile(datastore *this);
__int64 __fastcall datastore::CreateSharedCounter(datastore *this, _QWORD *a2, void **a3);
__int64 __fastcall datastore::GetCounterValue(unsigned int *a1);
__int64 __fastcall datastore::IncrementAndGetCounterValue(atomic_uint *a1);
__int64 __fastcall sub_FF0(unsigned int a1, atomic_uint *a2);
__int64 sub_1020();
void sub_10C0();
// int __cxa_finalize(void *);
// int __cxa_atexit(void (*lpfunc)(void *), void *obj, void *lpdso_handle);
__int64 __fastcall datastore::TruncateFile(datastore *this);
// char *strerror(int errnum);
__int64 __fastcall datastore::CreateSharedCounter(datastore *this, _QWORD *a2, void **a3);
__int64 __fastcall datastore::GetCounterValue(unsigned int *a1);
__int64 __fastcall datastore::IncrementAndGetCounterValue(atomic_uint *a1);
// int ftruncate(int fd, __off_t length);
// __int64 __errno(void); weak
// void *mmap(void *addr, size_t len, int prot, int flags, int fd, __off_t offset);
// unsigned __int64 getauxval(unsigned __int64 type);
// __int64 __fastcall __system_property_get(_QWORD, _QWORD); weak
// int strncmp(const char *s1, const char *s2, size_t n);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN *off_51C0 = &off_51C0; // weak
char byte_9428; // weak


//----- (0000000000000D30) ----------------------------------------------------
__int64 sub_D30()
{
  return __cxa_finalize(&off_51C0);
}
// 51C0: using guessed type _UNKNOWN *off_51C0;

//----- (0000000000000D40) ----------------------------------------------------
void sub_D40()
{
  ;
}

//----- (0000000000000D48) ----------------------------------------------------
void sub_D48()
{
  sub_D40();
}

//----- (0000000000000D50) ----------------------------------------------------
__int64 (*__fastcall sub_D50(__int64 (*result)(void)))(void)
{
  if ( result )
    return (__int64 (*)(void))result();
  return result;
}

//----- (0000000000000D64) ----------------------------------------------------
__int64 __fastcall sub_D64(void *obj)
{
  return __cxa_atexit((void (*)(void *))sub_D50, obj, &off_51C0);
}
// 51C0: using guessed type _UNKNOWN *off_51C0;

//----- (0000000000000D80) ----------------------------------------------------
__int64 __fastcall ThrowIoException(_JNIEnv *a1, const char *a2)
{
  jclass v4; // x0

  v4 = a1->functions->FindClass(a1, "java/io/IOException");
  if ( v4 )
    return ((__int64 (__fastcall *)(_JNIEnv *, jclass, const char *))a1->functions->ThrowNew)(a1, v4, a2);
  else
    return 0xFFFFFFFFLL;
}

//----- (0000000000000DDC) ----------------------------------------------------
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeTruncateFile(
        __int64 a1,
        int a2,
        datastore *this)
{
  int v4; // w0
  char *v5; // x20
  __int64 v6; // x0

  v4 = datastore::TruncateFile((datastore *)(unsigned int)this);
  if ( !v4 )
    return 0;
  v5 = strerror(v4);
  v6 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)a1 + 48LL))(a1, "java/io/IOException");
  if ( v6 )
    return (*(int (__fastcall **)(__int64, __int64, char *))(*(_QWORD *)a1 + 112LL))(a1, v6, v5);
  else
    return -1;
}

//----- (0000000000000E54) ----------------------------------------------------
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeCreateSharedCounter(
        __int64 a1,
        int a2,
        void **this)
{
  __int64 v4; // x8
  int SharedCounter; // w19
  char *v6; // x21
  __int64 v7; // x0
  _QWORD v9[2]; // [xsp+0h] [xbp-10h] BYREF

  v9[1] = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v9[0] = 0;
  SharedCounter = datastore::CreateSharedCounter((datastore *)(unsigned int)this, v9, this);
  if ( SharedCounter )
  {
    v6 = strerror(SharedCounter);
    v7 = (*(__int64 (__fastcall **)(__int64, const char *))(*(_QWORD *)a1 + 48LL))(a1, "java/io/IOException");
    if ( v7 )
      v4 = (*(int (__fastcall **)(__int64, __int64, char *))(*(_QWORD *)a1 + 112LL))(a1, v7, v6);
    else
      v4 = -1;
  }
  if ( SharedCounter )
    return v4;
  else
    return v9[0];
}
// EF0: variable 'v4' is possibly undefined

//----- (0000000000000F14) ----------------------------------------------------
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeGetCounterValue(
        __int64 a1,
        __int64 a2,
        unsigned int *a3)
{
  return datastore::GetCounterValue(a3);
}

//----- (0000000000000F2C) ----------------------------------------------------
__int64 __fastcall Java_androidx_datastore_core_NativeSharedCounter_nativeIncrementAndGetCounterValue(
        __int64 a1,
        __int64 a2,
        atomic_uint *a3)
{
  return datastore::IncrementAndGetCounterValue(a3);
}

//----- (0000000000000F44) ----------------------------------------------------
__int64 __fastcall datastore::TruncateFile(datastore *this)
{
  __int64 result; // x0

  result = ftruncate((int)this, 4);
  if ( (_DWORD)result )
    return *(unsigned int *)__errno();
  return result;
}
// 1170: using guessed type __int64 __errno(void);

//----- (0000000000000F68) ----------------------------------------------------
__int64 __fastcall datastore::CreateSharedCounter(datastore *this, _QWORD *a2, void **a3)
{
  void *v4; // x0
  unsigned int v5; // w8

  v4 = mmap(0, 4u, 3, 32769, (int)this, 0);
  if ( v4 == (void *)-1LL )
  {
    return *(unsigned int *)__errno();
  }
  else
  {
    v5 = 0;
    *a2 = v4;
  }
  return v5;
}
// 1170: using guessed type __int64 __errno(void);

//----- (0000000000000FC0) ----------------------------------------------------
__int64 __fastcall datastore::GetCounterValue(unsigned int *a1)
{
  return atomic_load(a1);
}

//----- (0000000000000FC8) ----------------------------------------------------
__int64 __fastcall datastore::IncrementAndGetCounterValue(atomic_uint *a1)
{
  return (unsigned int)sub_FF0(1u, a1) + 1;
}

//----- (0000000000000FF0) ----------------------------------------------------
__int64 __fastcall sub_FF0(unsigned int a1, atomic_uint *a2)
{
  __int64 result; // x0

  if ( byte_9428 )
    return atomic_fetch_add(a2, a1);
  do
    result = __ldaxr((unsigned int *)a2);
  while ( __stlxr(result + a1, (unsigned int *)a2) );
  return result;
}
// 9428: using guessed type char byte_9428;

//----- (0000000000001020) ----------------------------------------------------
__int64 sub_1020()
{
  __int64 result; // x0
  unsigned __int64 v1; // x19
  unsigned __int64 v2; // x19
  __int64 v3; // x8
  char s1[92]; // [xsp+4h] [xbp-6Ch] BYREF

  result = getauxval(0x10u);
  v1 = result;
  if ( (result & 0x100) != 0 )
  {
    result = __system_property_get("ro.arch", s1);
    if ( (int)result < 1 )
    {
      v3 = (v1 >> 8) & 1;
    }
    else
    {
      v2 = (v1 & 0x100) >> 8;
      result = strncmp(s1, "exynos9810", 0xAu);
      if ( (_DWORD)result )
        LODWORD(v3) = v2;
      else
        LODWORD(v3) = 0;
    }
    byte_9428 = (_DWORD)v3 != 0;
  }
  else
  {
    byte_9428 = 0;
  }
  return result;
}
// 11A0: using guessed type __int64 __fastcall __system_property_get(_QWORD, _QWORD);
// 9428: using guessed type char byte_9428;

//----- (00000000000010C0) ----------------------------------------------------
void sub_10C0()
{
  JUMPOUT(0);
}
// 10D0: control flows out of bounds to 0

//----- (0000000000001100) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall datastore::TruncateFile(datastore *this)
{
  return _ZN9datastore12TruncateFileEi(this);
}

//----- (0000000000001120) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall datastore::CreateSharedCounter(datastore *this, _QWORD *a2, void **a3)
{
  return _ZN9datastore19CreateSharedCounterEiPPv(this, a2, a3);
}

//----- (0000000000001140) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall datastore::GetCounterValue(unsigned int *a1)
{
  return _ZN9datastore15GetCounterValueEPNSt6__ndk16atomicIjEE(a1);
}

//----- (0000000000001150) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall datastore::IncrementAndGetCounterValue(atomic_uint *a1)
{
  return _ZN9datastore27IncrementAndGetCounterValueEPNSt6__ndk16atomicIjEE(a1);
}

// nfuncs=41 queued=21 decompiled=21 lumina nreq=0 worse=0 better=0
// ALL OK, 21 function(s) have been successfully decompiled
