/* This file was generated by the Hex-Rays decompiler version 9.1.0.250226.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 sub_2760();
void sub_2770();
void sub_2778();
__int64 (*__fastcall sub_2780(__int64 (*result)(void)))(void);
__int64 __fastcall sub_2794(void *obj); // idb
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_encrypt(_JNIEnv *a1, __int64 a2, __int64 a3);
jbyteArray __fastcall _JNIEnv::NewByteArray(_JNIEnv *this, unsigned int a2);
jbyteArray __fastcall melon4Key(_JNIEnv *a1);
__int64 __fastcall sha256(_JNIEnv *a1);
__int64 __fastcall aes256(_JNIEnv *a1, __int64 a2, int a3);
__int64 __fastcall _JNIEnv::DeleteLocalRef(__int64 a1, __int64 a2);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_decrypt(_JNIEnv *a1, __int64 a2, __int64 a3);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getEncCKey(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
jbyteArray __fastcall shuffle4Key(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getDecCKey(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_isShownBtn(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 __fastcall melonCrypto(_JNIEnv *a1, __int64 a2, int a3, __int64 a4, __int64 a5);
__int64 __fastcall byteArray2String(_JNIEnv *a1);
jclass __fastcall _JNIEnv::FindClass(_JNIEnv *this, const char *a2);
__int64 __fastcall _JNIEnv::GetMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 _JNIEnv::NewObject(__int64 a1, __int64 a2, __int64 a3, ...);
jstring __fastcall _JNIEnv::NewStringUTF(_JNIEnv *this, const char *a2);
__int64 _JNIEnv::CallBooleanMethod(__int64 a1, __int64 a2, __int64 a3, ...);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_isShownSongBtn(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_isShownLangBtn(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getBInfo(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 _JNIEnv::CallObjectMethod(__int64 a1, __int64 a2, __int64 a3, ...);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getProductState(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 _JNIEnv::CallIntMethod(__int64 a1, __int64 a2, __int64 a3, ...);
__int64 __fastcall currentTimeMillis(_JNIEnv *a1);
__int64 __fastcall convertString2Long(_JNIEnv *a1, __int64 a2, __int64 a3);
__int64 __fastcall equalsText(_JNIEnv *a1);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_patchAuthData(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 __fastcall string2ByteArray(_JNIEnv *a1, __int64 a2, __int64 a3);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_encodeBuyInfo(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, __int64 a7);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_melonCrypto(_JNIEnv *a1, __int64 a2, int a3, __int64 a4);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getAES256_1(_JNIEnv *a1, __int64 a2, int a3);
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getSHA256_1(_JNIEnv *a1);
jbyteArray __fastcall premium4Key(_JNIEnv *a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::GetByteArrayElements(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::SetByteArrayRegion(__int64 a1, __int64 a2, unsigned int a3, unsigned int a4, __int64 a5);
__int64 __fastcall _JNIEnv::ReleaseByteArrayElements(__int64 a1, __int64 a2, __int64 a3, unsigned int a4);
__int64 __fastcall _JNIEnv::GetStaticFieldID(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall _JNIEnv::GetStaticIntField(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::GetStaticMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 _JNIEnv::CallStaticObjectMethod(__int64 a1, __int64 a2, __int64 a3, ...);
__int64 __fastcall _JNIEnv::GetObjectClass(__int64 a1, __int64 a2);
__int64 _JNIEnv::CallVoidMethod(__int64 a1, __int64 a2, __int64 a3, ...);
__int64 __fastcall _JNIEnv::GetArrayLength(__int64 a1, __int64 a2);
__int64 _JNIEnv::CallStaticBooleanMethod(__int64 a1, __int64 a2, __int64 a3, ...);
__int64 _JNIEnv::CallStaticLongMethod(__int64 a1, __int64 a2, __int64 a3, ...);
void sub_5380();
// int __cxa_finalize(void *);
// int __cxa_atexit(void (*lpfunc)(void *), void *obj, void *lpdso_handle);
jbyteArray __fastcall _JNIEnv::NewByteArray(_JNIEnv *this, unsigned int a2);
jbyteArray __fastcall melon4Key(_JNIEnv *a1);
__int64 __fastcall sha256(_JNIEnv *a1);
__int64 __fastcall aes256(_JNIEnv *a1, __int64 a2, int a3);
__int64 __fastcall _JNIEnv::DeleteLocalRef(__int64 a1, __int64 a2);
__int64 __fastcall _JNIEnv::SetByteArrayRegion(__int64 a1, __int64 a2, unsigned int a3, unsigned int a4, __int64 a5);
jclass __fastcall _JNIEnv::FindClass(_JNIEnv *this, const char *a2);
__int64 __fastcall _JNIEnv::GetStaticMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
jstring __fastcall _JNIEnv::NewStringUTF(_JNIEnv *this, const char *a2);
__int64 __fastcall _JNIEnv::CallStaticObjectMethod(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::GetObjectClass(__int64 a1, __int64 a2);
__int64 __fastcall _JNIEnv::GetMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall _JNIEnv::CallVoidMethod(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::CallObjectMethod(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::NewObject(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::GetStaticFieldID(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall _JNIEnv::GetStaticIntField(__int64 a1, __int64 a2, __int64 a3);
jbyteArray __fastcall shuffle4Key(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4);
__int64 __fastcall _JNIEnv::GetArrayLength(__int64 a1, __int64 a2);
__int64 __fastcall _JNIEnv::GetByteArrayElements(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::ReleaseByteArrayElements(__int64 a1, __int64 a2, __int64 a3, unsigned int a4);
__int64 __fastcall melonCrypto(_JNIEnv *a1, __int64 a2, int a3, __int64 a4, __int64 a5);
__int64 __fastcall byteArray2String(_JNIEnv *a1);
__int64 __fastcall _JNIEnv::CallBooleanMethod(__int64 a1, __int64 a2, __int64 a3);
jbyteArray __fastcall premium4Key(_JNIEnv *a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::CallIntMethod(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall currentTimeMillis(_JNIEnv *a1);
__int64 __fastcall convertString2Long(_JNIEnv *a1, __int64 a2, __int64 a3);
__int64 __fastcall equalsText(_JNIEnv *a1);
__int64 __fastcall _JNIEnv::CallStaticLongMethod(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall _JNIEnv::CallStaticBooleanMethod(__int64 a1, __int64 a2, __int64 a3);
__int64 __fastcall string2ByteArray(_JNIEnv *a1, __int64 a2, __int64 a3);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN unk_1D91; // weak
_UNKNOWN unk_1DA0; // weak
_UNKNOWN *off_95D0 = &off_95D0; // weak
char *off_D8C8[10] =
{
  "ISDPOFFBTN",
  "ISSONGDPOFFBTN",
  "ISLANGDPOFFBTN",
  "BINFO",
  "Y",
  "ISPREMIUM",
  "PREMIUMDEVICEYN",
  "PREMIUMEXPIREDATE",
  "SERVERDATE",
  "PREMIUMLIMITDAY"
}; // weak
char *off_D8D0[9] =
{
  "ISSONGDPOFFBTN",
  "ISLANGDPOFFBTN",
  "BINFO",
  "Y",
  "ISPREMIUM",
  "PREMIUMDEVICEYN",
  "PREMIUMEXPIREDATE",
  "SERVERDATE",
  "PREMIUMLIMITDAY"
}; // weak
char *off_D8D8[8] =
{
  "ISLANGDPOFFBTN",
  "BINFO",
  "Y",
  "ISPREMIUM",
  "PREMIUMDEVICEYN",
  "PREMIUMEXPIREDATE",
  "SERVERDATE",
  "PREMIUMLIMITDAY"
}; // weak
char *off_D8E0[7] =
{
  "BINFO",
  "Y",
  "ISPREMIUM",
  "PREMIUMDEVICEYN",
  "PREMIUMEXPIREDATE",
  "SERVERDATE",
  "PREMIUMLIMITDAY"
}; // weak
char *off_D8E8[6] =
{
  "Y",
  "ISPREMIUM",
  "PREMIUMDEVICEYN",
  "PREMIUMEXPIREDATE",
  "SERVERDATE",
  "PREMIUMLIMITDAY"
}; // weak
char *off_D8F0[5] =
{
  "ISPREMIUM",
  "PREMIUMDEVICEYN",
  "PREMIUMEXPIREDATE",
  "SERVERDATE",
  "PREMIUMLIMITDAY"
}; // weak
char *off_D8F8[4] = { "PREMIUMDEVICEYN", "PREMIUMEXPIREDATE", "SERVERDATE", "PREMIUMLIMITDAY" }; // weak
char *off_D900[3] = { "PREMIUMEXPIREDATE", "SERVERDATE", "PREMIUMLIMITDAY" }; // weak
char *off_D908[2] = { "SERVERDATE", "PREMIUMLIMITDAY" }; // weak
char *off_D910 = "PREMIUMLIMITDAY"; // weak


//----- (0000000000002760) ----------------------------------------------------
__int64 sub_2760()
{
  return __cxa_finalize(&off_95D0);
}
// 95D0: using guessed type _UNKNOWN *off_95D0;

//----- (0000000000002770) ----------------------------------------------------
void sub_2770()
{
  ;
}

//----- (0000000000002778) ----------------------------------------------------
void sub_2778()
{
  sub_2770();
}

//----- (0000000000002780) ----------------------------------------------------
__int64 (*__fastcall sub_2780(__int64 (*result)(void)))(void)
{
  if ( result )
    return (__int64 (*)(void))result();
  return result;
}

//----- (0000000000002794) ----------------------------------------------------
__int64 __fastcall sub_2794(void *obj)
{
  return __cxa_atexit((void (*)(void *))sub_2780, obj, &off_95D0);
}
// 95D0: using guessed type _UNKNOWN *off_95D0;

//----- (00000000000027B0) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_encrypt(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  __int64 v4; // [xsp+0h] [xbp-40h]
  __int64 v5; // [xsp+8h] [xbp-38h]
  jbyteArray v6; // [xsp+10h] [xbp-30h]
  jbyteArray v7; // [xsp+18h] [xbp-28h]

  if ( !a3 )
    return 0;
  v7 = _JNIEnv::NewByteArray(a1, 0x10u);
  v6 = melon4Key(a1);
  if ( !v6 )
    return 0;
  v5 = sha256(a1);
  if ( !v5 )
    return 0;
  v4 = aes256(a1, a2, 1);
  _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v6);
  _JNIEnv::DeleteLocalRef((__int64)a1, v5);
  if ( v7 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v7);
  return v4;
}
// 285C: conditional instruction was optimized away because %var_30.8!=0
// 2878: conditional instruction was optimized away because %var_38.8!=0

//----- (00000000000028C8) ----------------------------------------------------
jbyteArray __fastcall _JNIEnv::NewByteArray(_JNIEnv *this, unsigned int a2)
{
  return this->functions->NewByteArray(this, a2);
}

//----- (00000000000028FC) ----------------------------------------------------
jbyteArray __fastcall melon4Key(_JNIEnv *a1)
{
  jbyteArray v2; // [xsp+8h] [xbp-18h]

  v2 = _JNIEnv::NewByteArray(a1, 0xFu);
  _JNIEnv::SetByteArrayRegion((__int64)a1, (__int64)v2, 0, 0xFu, (__int64)&unk_1D91);
  return v2;
}

//----- (0000000000002950) ----------------------------------------------------
__int64 __fastcall sha256(_JNIEnv *a1)
{
  __int64 StaticMethodID; // [xsp+10h] [xbp-60h]
  __int64 v3; // [xsp+20h] [xbp-50h]
  __int64 v4; // [xsp+28h] [xbp-48h]
  __int64 MethodID; // [xsp+30h] [xbp-40h]
  __int64 ObjectClass; // [xsp+38h] [xbp-38h]
  __int64 v7; // [xsp+40h] [xbp-30h]
  jclass Class; // [xsp+50h] [xbp-20h]

  Class = _JNIEnv::FindClass(a1, "java/security/MessageDigest");
  StaticMethodID = _JNIEnv::GetStaticMethodID(
                     (__int64)a1,
                     (__int64)Class,
                     (__int64)"getInstance",
                     (__int64)"(Ljava/lang/String;)Ljava/security/MessageDigest;");
  _JNIEnv::NewStringUTF(a1, "SHA-256");
  v7 = _JNIEnv::CallStaticObjectMethod((__int64)a1, (__int64)Class, StaticMethodID);
  ObjectClass = _JNIEnv::GetObjectClass((__int64)a1, v7);
  MethodID = _JNIEnv::GetMethodID((__int64)a1, ObjectClass, (__int64)"update", (__int64)"([B)V");
  _JNIEnv::CallVoidMethod((__int64)a1, v7, MethodID);
  v4 = _JNIEnv::GetMethodID((__int64)a1, ObjectClass, (__int64)"digest", (__int64)"()[B");
  v3 = _JNIEnv::CallObjectMethod((__int64)a1, v7, v4);
  if ( ObjectClass )
    _JNIEnv::DeleteLocalRef((__int64)a1, ObjectClass);
  if ( v7 )
    _JNIEnv::DeleteLocalRef((__int64)a1, v7);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  return v3;
}

//----- (0000000000002AB8) ----------------------------------------------------
__int64 __fastcall aes256(_JNIEnv *a1, __int64 a2, int a3)
{
  __int64 StaticMethodID; // [xsp+10h] [xbp-E0h]
  __int64 MethodID; // [xsp+28h] [xbp-C8h]
  __int64 v6; // [xsp+48h] [xbp-A8h]
  __int64 v7; // [xsp+50h] [xbp-A0h]
  __int64 v8; // [xsp+58h] [xbp-98h]
  __int64 ObjectClass; // [xsp+60h] [xbp-90h]
  __int64 v10; // [xsp+68h] [xbp-88h]
  __int64 StaticFieldID; // [xsp+80h] [xbp-70h]
  jclass v12; // [xsp+88h] [xbp-68h]
  __int64 v13; // [xsp+90h] [xbp-60h]
  __int64 v14; // [xsp+98h] [xbp-58h]
  jclass v15; // [xsp+A0h] [xbp-50h]
  __int64 v16; // [xsp+A8h] [xbp-48h]
  jclass Class; // [xsp+B8h] [xbp-38h]

  Class = _JNIEnv::FindClass(a1, "javax/crypto/spec/SecretKeySpec");
  MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"([BLjava/lang/String;)V");
  _JNIEnv::NewStringUTF(a1, "AES");
  v16 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
  v15 = _JNIEnv::FindClass(a1, "javax/crypto/spec/IvParameterSpec");
  v14 = _JNIEnv::GetMethodID((__int64)a1, (__int64)v15, (__int64)"<init>", (__int64)"([B)V");
  v13 = _JNIEnv::NewObject((__int64)a1, (__int64)v15, v14);
  v12 = _JNIEnv::FindClass(a1, "javax/crypto/Cipher");
  if ( a3 == 1 )
    StaticFieldID = _JNIEnv::GetStaticFieldID((__int64)a1, (__int64)v12, (__int64)"ENCRYPT_MODE", (__int64)"I");
  else
    StaticFieldID = _JNIEnv::GetStaticFieldID((__int64)a1, (__int64)v12, (__int64)"DECRYPT_MODE", (__int64)"I");
  _JNIEnv::GetStaticIntField((__int64)a1, (__int64)v12, StaticFieldID);
  StaticMethodID = _JNIEnv::GetStaticMethodID(
                     (__int64)a1,
                     (__int64)v12,
                     (__int64)"getInstance",
                     (__int64)"(Ljava/lang/String;)Ljavax/crypto/Cipher;");
  _JNIEnv::NewStringUTF(a1, "AES/CBC/PKCS5Padding");
  v10 = _JNIEnv::CallStaticObjectMethod((__int64)a1, (__int64)v12, StaticMethodID);
  ObjectClass = _JNIEnv::GetObjectClass((__int64)a1, v10);
  v8 = _JNIEnv::GetMethodID(
         (__int64)a1,
         ObjectClass,
         (__int64)"init",
         (__int64)"(ILjava/security/Key;Ljava/security/spec/AlgorithmParameterSpec;)V");
  _JNIEnv::CallVoidMethod((__int64)a1, v10, v8);
  v7 = _JNIEnv::GetMethodID((__int64)a1, ObjectClass, (__int64)"doFinal", (__int64)"([B)[B");
  v6 = _JNIEnv::CallObjectMethod((__int64)a1, v10, v7);
  if ( v16 )
    _JNIEnv::DeleteLocalRef((__int64)a1, v16);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  if ( v13 )
    _JNIEnv::DeleteLocalRef((__int64)a1, v13);
  if ( v15 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v15);
  if ( ObjectClass )
    _JNIEnv::DeleteLocalRef((__int64)a1, ObjectClass);
  if ( v10 )
    _JNIEnv::DeleteLocalRef((__int64)a1, v10);
  if ( v12 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v12);
  return v6;
}

//----- (0000000000002DE0) ----------------------------------------------------
__int64 __fastcall _JNIEnv::DeleteLocalRef(__int64 a1, __int64 a2)
{
  return (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)a1 + 184LL))(a1, a2);
}

//----- (0000000000002E14) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_decrypt(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  __int64 v4; // [xsp+0h] [xbp-40h]
  __int64 v5; // [xsp+8h] [xbp-38h]
  jbyteArray v6; // [xsp+10h] [xbp-30h]
  jbyteArray v7; // [xsp+18h] [xbp-28h]

  if ( !a3 )
    return 0;
  v7 = _JNIEnv::NewByteArray(a1, 0x10u);
  v6 = melon4Key(a1);
  if ( !v6 )
    return 0;
  v5 = sha256(a1);
  if ( !v5 )
    return 0;
  v4 = aes256(a1, a2, 0);
  _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v6);
  _JNIEnv::DeleteLocalRef((__int64)a1, v5);
  if ( v7 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v7);
  return v4;
}
// 2EC0: conditional instruction was optimized away because %var_30.8!=0
// 2EDC: conditional instruction was optimized away because %var_38.8!=0

//----- (0000000000002F2C) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getEncCKey(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  __int64 v8; // [xsp+0h] [xbp-60h]
  __int64 v9; // [xsp+8h] [xbp-58h]
  jbyteArray v10; // [xsp+10h] [xbp-50h]
  jbyteArray v11; // [xsp+18h] [xbp-48h]

  if ( !a4 || !a6 || !a7 )
    return 0;
  v11 = _JNIEnv::NewByteArray(a1, 0x10u);
  v10 = shuffle4Key(a1, a2, a4, a6);
  if ( !v10 )
    return 0;
  v9 = sha256(a1);
  if ( !v9 )
    return 0;
  v8 = aes256(a1, a2, 1);
  _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v10);
  _JNIEnv::DeleteLocalRef((__int64)a1, v9);
  if ( v11 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v11);
  return v8;
}
// 3008: conditional instruction was optimized away because %var_50.8!=0
// 3024: conditional instruction was optimized away because %var_58.8!=0

//----- (0000000000003074) ----------------------------------------------------
jbyteArray __fastcall shuffle4Key(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4)
{
  jbyteArray v5; // [xsp+18h] [xbp-48h]
  __int64 v6; // [xsp+20h] [xbp-40h]
  __int64 ByteArrayElements; // [xsp+28h] [xbp-38h]
  unsigned int v8; // [xsp+38h] [xbp-28h]
  unsigned int ArrayLength; // [xsp+3Ch] [xbp-24h]

  ArrayLength = _JNIEnv::GetArrayLength((__int64)a1, a3);
  v8 = _JNIEnv::GetArrayLength((__int64)a1, a4);
  ByteArrayElements = _JNIEnv::GetByteArrayElements((__int64)a1, a3, 0);
  v6 = _JNIEnv::GetByteArrayElements((__int64)a1, a4, 0);
  v5 = _JNIEnv::NewByteArray(a1, ArrayLength + 11 + v8);
  _JNIEnv::SetByteArrayRegion((__int64)a1, (__int64)v5, 0, 0xBu, (__int64)&unk_1DA0);
  _JNIEnv::SetByteArrayRegion((__int64)a1, (__int64)v5, 0xBu, ArrayLength, ByteArrayElements);
  _JNIEnv::SetByteArrayRegion((__int64)a1, (__int64)v5, ArrayLength + 11, v8, v6);
  _JNIEnv::ReleaseByteArrayElements((__int64)a1, a3, ByteArrayElements, 0);
  _JNIEnv::ReleaseByteArrayElements((__int64)a1, a4, v6, 0);
  return v5;
}

//----- (0000000000003194) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getDecCKey(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  __int64 v8; // [xsp+0h] [xbp-60h]
  __int64 v9; // [xsp+8h] [xbp-58h]
  jbyteArray v10; // [xsp+10h] [xbp-50h]
  jbyteArray v11; // [xsp+18h] [xbp-48h]

  if ( !a4 || !a6 || !a7 )
    return 0;
  v11 = _JNIEnv::NewByteArray(a1, 0x10u);
  v10 = shuffle4Key(a1, a2, a4, a6);
  if ( !v10 )
    return 0;
  v9 = sha256(a1);
  if ( !v9 )
    return 0;
  v8 = aes256(a1, a2, 0);
  _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v10);
  _JNIEnv::DeleteLocalRef((__int64)a1, v9);
  if ( v11 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v11);
  return v8;
}
// 3270: conditional instruction was optimized away because %var_50.8!=0
// 328C: conditional instruction was optimized away because %var_58.8!=0

//----- (00000000000032DC) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_isShownBtn(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  unsigned __int8 v8; // [xsp+7h] [xbp-79h]
  __int64 v9; // [xsp+8h] [xbp-78h]
  jstring v10; // [xsp+10h] [xbp-70h]
  __int64 v11; // [xsp+18h] [xbp-68h]
  __int64 MethodID; // [xsp+20h] [xbp-60h]
  jclass Class; // [xsp+28h] [xbp-58h]
  __int64 v14; // [xsp+30h] [xbp-50h]
  __int64 v15; // [xsp+38h] [xbp-48h]

  if ( a6 && a7 )
  {
    v15 = melonCrypto(a1, a2, 0, a4, a6);
    if ( v15 )
    {
      v14 = byteArray2String(a1);
      Class = _JNIEnv::FindClass(a1, "org/json/JSONObject");
      MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"(Ljava/lang/String;)V");
      v11 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
      if ( v11 )
      {
        v10 = _JNIEnv::NewStringUTF(a1, off_D8C8[0]);
        v9 = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"getBoolean", (__int64)"(Ljava/lang/String;)Z");
        v8 = _JNIEnv::CallBooleanMethod((__int64)a1, v11, v9);
        if ( v10 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v10);
        _JNIEnv::DeleteLocalRef((__int64)a1, v11);
        if ( Class )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
        if ( v14 )
          _JNIEnv::DeleteLocalRef((__int64)a1, v14);
        _JNIEnv::DeleteLocalRef((__int64)a1, v15);
        return v8;
      }
      else
      {
        return 0;
      }
    }
    else
    {
      return 0;
    }
  }
  else
  {
    return 0;
  }
}
// 3438: conditional instruction was optimized away because %var_68.8!=0
// 348C: conditional instruction was optimized away because %var_48.8!=0
// D8C8: using guessed type char *off_D8C8[10];

//----- (00000000000034C0) ----------------------------------------------------
__int64 __fastcall melonCrypto(_JNIEnv *a1, __int64 a2, int a3, __int64 a4, __int64 a5)
{
  __int64 v6; // [xsp+10h] [xbp-60h]
  __int64 ByteArrayElements; // [xsp+18h] [xbp-58h]
  __int64 v8; // [xsp+20h] [xbp-50h]
  jbyteArray v9; // [xsp+30h] [xbp-40h]

  v9 = _JNIEnv::NewByteArray(a1, 0x10u);
  premium4Key(a1, a2, a5);
  v8 = sha256(a1);
  if ( !v8 )
    return 0;
  ByteArrayElements = _JNIEnv::GetByteArrayElements((__int64)a1, v8, 0);
  _JNIEnv::SetByteArrayRegion((__int64)a1, (__int64)v9, 0, 0x10u, ByteArrayElements);
  _JNIEnv::ReleaseByteArrayElements((__int64)a1, v8, ByteArrayElements, 0);
  v6 = aes256(a1, a2, a3);
  _JNIEnv::DeleteLocalRef((__int64)a1, v8);
  if ( v9 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v9);
  return v6;
}

//----- (00000000000035E8) ----------------------------------------------------
__int64 __fastcall byteArray2String(_JNIEnv *a1)
{
  __int64 v2; // [xsp+0h] [xbp-30h]
  __int64 MethodID; // [xsp+8h] [xbp-28h]
  jclass Class; // [xsp+10h] [xbp-20h]

  Class = _JNIEnv::FindClass(a1, "java/lang/String");
  MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"([B)V");
  v2 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  return v2;
}

//----- (0000000000003678) ----------------------------------------------------
jclass __fastcall _JNIEnv::FindClass(_JNIEnv *this, const char *a2)
{
  return this->functions->FindClass(this, a2);
}

//----- (00000000000036AC) ----------------------------------------------------
__int64 __fastcall _JNIEnv::GetMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, __int64, __int64))(*(_QWORD *)a1 + 264LL))(a1, a2, a3, a4);
}

//----- (00000000000036F0) ----------------------------------------------------
__int64 _JNIEnv::NewObject(__int64 a1, __int64 a2, __int64 a3, ...)
{
  __int64 (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+E0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+108h] [xbp-28h] BYREF
  __int64 v7; // [xsp+128h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(__int64 (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 232LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (00000000000037EC) ----------------------------------------------------
jstring __fastcall _JNIEnv::NewStringUTF(_JNIEnv *this, const char *a2)
{
  return this->functions->NewStringUTF(this, a2);
}

//----- (0000000000003820) ----------------------------------------------------
__int64 _JNIEnv::CallBooleanMethod(__int64 a1, __int64 a2, __int64 a3, ...)
{
  unsigned __int8 (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+E0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+108h] [xbp-28h] BYREF
  __int64 v7; // [xsp+128h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(unsigned __int8 (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 304LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (000000000000391C) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_isShownSongBtn(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  unsigned __int8 v8; // [xsp+7h] [xbp-79h]
  __int64 v9; // [xsp+8h] [xbp-78h]
  jstring v10; // [xsp+10h] [xbp-70h]
  __int64 v11; // [xsp+18h] [xbp-68h]
  __int64 MethodID; // [xsp+20h] [xbp-60h]
  jclass Class; // [xsp+28h] [xbp-58h]
  __int64 v14; // [xsp+30h] [xbp-50h]
  __int64 v15; // [xsp+38h] [xbp-48h]

  if ( a6 && a7 )
  {
    v15 = melonCrypto(a1, a2, 0, a4, a6);
    if ( v15 )
    {
      v14 = byteArray2String(a1);
      Class = _JNIEnv::FindClass(a1, "org/json/JSONObject");
      MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"(Ljava/lang/String;)V");
      v11 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
      if ( v11 )
      {
        v10 = _JNIEnv::NewStringUTF(a1, off_D8D0[0]);
        v9 = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"getBoolean", (__int64)"(Ljava/lang/String;)Z");
        v8 = _JNIEnv::CallBooleanMethod((__int64)a1, v11, v9);
        if ( v10 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v10);
        _JNIEnv::DeleteLocalRef((__int64)a1, v11);
        if ( Class )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
        if ( v14 )
          _JNIEnv::DeleteLocalRef((__int64)a1, v14);
        _JNIEnv::DeleteLocalRef((__int64)a1, v15);
        return v8;
      }
      else
      {
        return 0;
      }
    }
    else
    {
      return 0;
    }
  }
  else
  {
    return 0;
  }
}
// 3A78: conditional instruction was optimized away because %var_68.8!=0
// 3ACC: conditional instruction was optimized away because %var_48.8!=0
// D8D0: using guessed type char *off_D8D0[9];

//----- (0000000000003B00) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_isShownLangBtn(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  unsigned __int8 v8; // [xsp+7h] [xbp-79h]
  __int64 v9; // [xsp+8h] [xbp-78h]
  jstring v10; // [xsp+10h] [xbp-70h]
  __int64 v11; // [xsp+18h] [xbp-68h]
  __int64 MethodID; // [xsp+20h] [xbp-60h]
  jclass Class; // [xsp+28h] [xbp-58h]
  __int64 v14; // [xsp+30h] [xbp-50h]
  __int64 v15; // [xsp+38h] [xbp-48h]

  if ( a6 && a7 )
  {
    v15 = melonCrypto(a1, a2, 0, a4, a6);
    if ( v15 )
    {
      v14 = byteArray2String(a1);
      Class = _JNIEnv::FindClass(a1, "org/json/JSONObject");
      MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"(Ljava/lang/String;)V");
      v11 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
      if ( v11 )
      {
        v10 = _JNIEnv::NewStringUTF(a1, off_D8D8[0]);
        v9 = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"getBoolean", (__int64)"(Ljava/lang/String;)Z");
        v8 = _JNIEnv::CallBooleanMethod((__int64)a1, v11, v9);
        if ( v10 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v10);
        _JNIEnv::DeleteLocalRef((__int64)a1, v11);
        if ( Class )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
        if ( v14 )
          _JNIEnv::DeleteLocalRef((__int64)a1, v14);
        _JNIEnv::DeleteLocalRef((__int64)a1, v15);
        return v8;
      }
      else
      {
        return 0;
      }
    }
    else
    {
      return 0;
    }
  }
  else
  {
    return 0;
  }
}
// 3C5C: conditional instruction was optimized away because %var_68.8!=0
// 3CB0: conditional instruction was optimized away because %var_48.8!=0
// D8D8: using guessed type char *off_D8D8[8];

//----- (0000000000003CE4) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getBInfo(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  __int64 v8; // [xsp+0h] [xbp-80h]
  __int64 v9; // [xsp+8h] [xbp-78h]
  jstring v10; // [xsp+10h] [xbp-70h]
  __int64 v11; // [xsp+18h] [xbp-68h]
  __int64 MethodID; // [xsp+20h] [xbp-60h]
  jclass Class; // [xsp+28h] [xbp-58h]
  __int64 v14; // [xsp+30h] [xbp-50h]
  __int64 v15; // [xsp+38h] [xbp-48h]

  if ( !a6 || !a7 )
    return 0;
  v15 = melonCrypto(a1, a2, 0, a4, a6);
  if ( !v15 )
    return 0;
  v14 = byteArray2String(a1);
  Class = _JNIEnv::FindClass(a1, "org/json/JSONObject");
  MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"(Ljava/lang/String;)V");
  v11 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
  if ( !v11 )
    return 0;
  v10 = _JNIEnv::NewStringUTF(a1, off_D8E0[0]);
  v9 = _JNIEnv::GetMethodID(
         (__int64)a1,
         (__int64)Class,
         (__int64)"getString",
         (__int64)"(Ljava/lang/String;)Ljava/lang/String;");
  v8 = _JNIEnv::CallObjectMethod((__int64)a1, v11, v9);
  if ( !v8 )
    return 0;
  if ( v10 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v10);
  _JNIEnv::DeleteLocalRef((__int64)a1, v11);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  if ( v14 )
    _JNIEnv::DeleteLocalRef((__int64)a1, v14);
  _JNIEnv::DeleteLocalRef((__int64)a1, v15);
  return v8;
}
// 3E54: conditional instruction was optimized away because %var_68.8!=0
// 3EA8: conditional instruction was optimized away because %var_48.8!=0
// D8E0: using guessed type char *off_D8E0[7];

//----- (0000000000003EDC) ----------------------------------------------------
__int64 _JNIEnv::CallObjectMethod(__int64 a1, __int64 a2, __int64 a3, ...)
{
  __int64 (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+E0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+108h] [xbp-28h] BYREF
  __int64 v7; // [xsp+128h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(__int64 (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 280LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (0000000000003FD8) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getProductState(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  unsigned int v8; // [xsp+14h] [xbp-FCh]
  __int64 v9; // [xsp+18h] [xbp-F8h]
  __int64 v10; // [xsp+20h] [xbp-F0h]
  __int64 v11; // [xsp+28h] [xbp-E8h]
  __int64 v12; // [xsp+30h] [xbp-E0h]
  int v13; // [xsp+3Ch] [xbp-D4h]
  __int64 v14; // [xsp+40h] [xbp-D0h]
  __int64 v15; // [xsp+48h] [xbp-C8h]
  char v16; // [xsp+5Fh] [xbp-B1h]
  jstring v17; // [xsp+60h] [xbp-B0h]
  jstring v18; // [xsp+68h] [xbp-A8h]
  jstring v19; // [xsp+70h] [xbp-A0h]
  jstring v20; // [xsp+78h] [xbp-98h]
  jstring v21; // [xsp+80h] [xbp-90h]
  jstring v22; // [xsp+88h] [xbp-88h]
  __int64 v23; // [xsp+90h] [xbp-80h]
  __int64 v24; // [xsp+98h] [xbp-78h]
  __int64 v25; // [xsp+A0h] [xbp-70h]
  __int64 v26; // [xsp+A8h] [xbp-68h]
  __int64 MethodID; // [xsp+B0h] [xbp-60h]
  jclass Class; // [xsp+B8h] [xbp-58h]
  __int64 v29; // [xsp+C0h] [xbp-50h]
  __int64 v30; // [xsp+C8h] [xbp-48h]

  if ( a6 && a7 )
  {
    v30 = melonCrypto(a1, a2, 0, a4, a6);
    if ( v30 )
    {
      v29 = byteArray2String(a1);
      Class = _JNIEnv::FindClass(a1, "org/json/JSONObject");
      MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"(Ljava/lang/String;)V");
      v26 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
      if ( v26 )
      {
        v25 = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"getBoolean", (__int64)"(Ljava/lang/String;)Z");
        v24 = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"getInt", (__int64)"(Ljava/lang/String;)I");
        v23 = _JNIEnv::GetMethodID(
                (__int64)a1,
                (__int64)Class,
                (__int64)"getString",
                (__int64)"(Ljava/lang/String;)Ljava/lang/String;");
        v22 = _JNIEnv::NewStringUTF(a1, off_D8E8[0]);
        v21 = _JNIEnv::NewStringUTF(a1, off_D8F0[0]);
        v20 = _JNIEnv::NewStringUTF(a1, off_D8F8[0]);
        v19 = _JNIEnv::NewStringUTF(a1, off_D900[0]);
        v18 = _JNIEnv::NewStringUTF(a1, off_D908[0]);
        v17 = _JNIEnv::NewStringUTF(a1, off_D910);
        v16 = _JNIEnv::CallBooleanMethod((__int64)a1, v26, v25);
        if ( v16 )
        {
          if ( !_JNIEnv::CallObjectMethod((__int64)a1, v26, v23) )
            return 1;
          v15 = _JNIEnv::CallObjectMethod((__int64)a1, v26, v23);
          if ( !v15 )
            return 1;
          v14 = _JNIEnv::CallObjectMethod((__int64)a1, v26, v23);
          if ( !v14 )
            return 1;
          v13 = _JNIEnv::CallIntMethod((__int64)a1, v26, v24);
          if ( !v13 )
            return 1;
        }
        if ( v16 )
        {
          v12 = currentTimeMillis(a1);
          if ( !v12 )
            return 1;
          v11 = convertString2Long(a1, a2, v15);
          if ( !v11 )
            return 1;
          v10 = convertString2Long(a1, a2, v14);
          if ( !v10 )
            return 1;
          v9 = v10 + 86400000LL * v13;
        }
        if ( v16 )
        {
          if ( v11 >= v12 )
          {
            if ( (unsigned __int8)equalsText(a1) )
            {
              if ( v9 >= v12 )
                v8 = 5;
              else
                v8 = 4;
            }
            else
            {
              v8 = 3;
            }
          }
          else
          {
            v8 = 2;
          }
        }
        else
        {
          v8 = 1;
        }
        if ( v17 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v17);
        if ( v18 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v18);
        if ( v19 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v19);
        if ( v20 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v20);
        if ( v21 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v21);
        if ( v22 )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v22);
        _JNIEnv::DeleteLocalRef((__int64)a1, v26);
        if ( Class )
          _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
        if ( v29 )
          _JNIEnv::DeleteLocalRef((__int64)a1, v29);
        _JNIEnv::DeleteLocalRef((__int64)a1, v30);
        return v8;
      }
      else
      {
        return 1;
      }
    }
    else
    {
      return 1;
    }
  }
  else
  {
    return 1;
  }
}
// 4520: conditional instruction was optimized away because %0xA8.8!=0
// 458C: conditional instruction was optimized away because %0xC8.8!=0
// 4340: variable 'v15' is possibly undefined
// 4370: variable 'v14' is possibly undefined
// 4394: variable 'v13' is possibly undefined
// 43DC: variable 'v11' is possibly undefined
// 43DC: variable 'v12' is possibly undefined
// 442C: variable 'v9' is possibly undefined
// D8E8: using guessed type char *off_D8E8[6];
// D8F0: using guessed type char *off_D8F0[5];
// D8F8: using guessed type char *off_D8F8[4];
// D900: using guessed type char *off_D900[3];
// D908: using guessed type char *off_D908[2];
// D910: using guessed type char *off_D910;

//----- (00000000000045C8) ----------------------------------------------------
__int64 _JNIEnv::CallIntMethod(__int64 a1, __int64 a2, __int64 a3, ...)
{
  unsigned int (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+E0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+108h] [xbp-28h] BYREF
  __int64 v7; // [xsp+128h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(unsigned int (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 400LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (00000000000046C4) ----------------------------------------------------
__int64 __fastcall currentTimeMillis(_JNIEnv *a1)
{
  __int64 v2; // [xsp+8h] [xbp-28h]
  __int64 StaticMethodID; // [xsp+10h] [xbp-20h]
  jclass Class; // [xsp+18h] [xbp-18h]

  Class = _JNIEnv::FindClass(a1, "java/lang/System");
  StaticMethodID = _JNIEnv::GetStaticMethodID((__int64)a1, (__int64)Class, (__int64)"currentTimeMillis", (__int64)"()J");
  v2 = _JNIEnv::CallStaticLongMethod((__int64)a1, (__int64)Class, StaticMethodID);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  return v2;
}

//----- (000000000000474C) ----------------------------------------------------
__int64 __fastcall convertString2Long(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  __int64 v4; // [xsp+8h] [xbp-38h]
  __int64 StaticMethodID; // [xsp+10h] [xbp-30h]
  jclass Class; // [xsp+18h] [xbp-28h]

  if ( !a3 )
    return 0;
  Class = _JNIEnv::FindClass(a1, "com/iloen/melon/utils/DateUtils");
  StaticMethodID = _JNIEnv::GetStaticMethodID(
                     (__int64)a1,
                     (__int64)Class,
                     (__int64)"convertString2Long",
                     (__int64)"(Ljava/lang/String;)J");
  v4 = _JNIEnv::CallStaticLongMethod((__int64)a1, (__int64)Class, StaticMethodID);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  return v4;
}

//----- (00000000000047FC) ----------------------------------------------------
__int64 __fastcall equalsText(_JNIEnv *a1)
{
  unsigned __int8 v2; // [xsp+Fh] [xbp-31h]
  __int64 StaticMethodID; // [xsp+10h] [xbp-30h]
  jclass Class; // [xsp+18h] [xbp-28h]

  Class = _JNIEnv::FindClass(a1, "android/text/TextUtils");
  StaticMethodID = _JNIEnv::GetStaticMethodID(
                     (__int64)a1,
                     (__int64)Class,
                     (__int64)"equals",
                     (__int64)"(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z");
  v2 = _JNIEnv::CallStaticBooleanMethod((__int64)a1, (__int64)Class, StaticMethodID);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  return v2;
}

//----- (0000000000004894) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_patchAuthData(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  __int64 v8; // [xsp+0h] [xbp-A0h]
  __int64 v9; // [xsp+10h] [xbp-90h]
  __int64 v10; // [xsp+18h] [xbp-88h]
  __int64 v11; // [xsp+20h] [xbp-80h]
  jstring v12; // [xsp+28h] [xbp-78h]
  jstring v13; // [xsp+30h] [xbp-70h]
  __int64 v14; // [xsp+38h] [xbp-68h]
  __int64 MethodID; // [xsp+40h] [xbp-60h]
  jclass Class; // [xsp+48h] [xbp-58h]
  __int64 v17; // [xsp+50h] [xbp-50h]
  __int64 v18; // [xsp+58h] [xbp-48h]

  if ( !a6 || !a7 )
    return 0;
  v18 = melonCrypto(a1, a2, 0, a4, a6);
  if ( !v18 )
    return 0;
  v17 = byteArray2String(a1);
  Class = _JNIEnv::FindClass(a1, "org/json/JSONObject");
  MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"<init>", (__int64)"(Ljava/lang/String;)V");
  v14 = _JNIEnv::NewObject((__int64)a1, (__int64)Class, MethodID);
  if ( !v14 )
    return 0;
  v13 = _JNIEnv::NewStringUTF(a1, off_D8E8[0]);
  v12 = _JNIEnv::NewStringUTF(a1, off_D8F8[0]);
  v11 = _JNIEnv::GetMethodID(
          (__int64)a1,
          (__int64)Class,
          (__int64)"put",
          (__int64)"(Ljava/lang/String;Ljava/lang/Object;)Lorg/json/JSONObject;");
  _JNIEnv::CallObjectMethod((__int64)a1, v14, v11);
  v10 = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"toString", (__int64)"()Ljava/lang/String;");
  v9 = _JNIEnv::CallObjectMethod((__int64)a1, v14, v10);
  string2ByteArray(a1, a2, v9);
  v8 = melonCrypto(a1, a2, 1, a4, a6);
  if ( v13 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v13);
  if ( v12 )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)v12);
  _JNIEnv::DeleteLocalRef((__int64)a1, v14);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  if ( v17 )
    _JNIEnv::DeleteLocalRef((__int64)a1, v17);
  _JNIEnv::DeleteLocalRef((__int64)a1, v18);
  return v8;
}
// 4A88: conditional instruction was optimized away because %var_68.8!=0
// 4ADC: conditional instruction was optimized away because %var_48.8!=0
// D8E8: using guessed type char *off_D8E8[6];
// D8F8: using guessed type char *off_D8F8[4];

//----- (0000000000004B10) ----------------------------------------------------
__int64 __fastcall string2ByteArray(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  __int64 v4; // [xsp+0h] [xbp-30h]
  __int64 MethodID; // [xsp+8h] [xbp-28h]
  jclass Class; // [xsp+10h] [xbp-20h]

  Class = _JNIEnv::FindClass(a1, "java/lang/String");
  MethodID = _JNIEnv::GetMethodID((__int64)a1, (__int64)Class, (__int64)"getBytes", (__int64)"()[B");
  v4 = _JNIEnv::CallObjectMethod((__int64)a1, a3, MethodID);
  if ( Class )
    _JNIEnv::DeleteLocalRef((__int64)a1, (__int64)Class);
  return v4;
}

//----- (0000000000004B9C) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_encodeBuyInfo(
        _JNIEnv *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        __int64 a7)
{
  if ( a6 && a7 )
    return melonCrypto(a1, a2, 1, a4, a6);
  else
    return 0;
}

//----- (0000000000004C18) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_melonCrypto(
        _JNIEnv *a1,
        __int64 a2,
        int a3,
        __int64 a4)
{
  return melonCrypto(a1, a2, a3, 0, a4);
}

//----- (0000000000004C60) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getAES256_1(_JNIEnv *a1, __int64 a2, int a3)
{
  return aes256(a1, a2, a3);
}

//----- (0000000000004CAC) ----------------------------------------------------
__int64 __fastcall Java_com_iloen_melon_utils_cipher_MelonCryptoManager_getSHA256_1(_JNIEnv *a1)
{
  return sha256(a1);
}

//----- (0000000000004CE0) ----------------------------------------------------
jbyteArray __fastcall premium4Key(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  jbyteArray v4; // [xsp+10h] [xbp-30h]
  __int64 ByteArrayElements; // [xsp+18h] [xbp-28h]
  unsigned int ArrayLength; // [xsp+24h] [xbp-1Ch]

  ArrayLength = _JNIEnv::GetArrayLength((__int64)a1, a3);
  ByteArrayElements = _JNIEnv::GetByteArrayElements((__int64)a1, a3, 0);
  v4 = _JNIEnv::NewByteArray(a1, ArrayLength + 11);
  _JNIEnv::SetByteArrayRegion((__int64)a1, (__int64)v4, 0, 0xBu, (__int64)&unk_1DA0);
  _JNIEnv::SetByteArrayRegion((__int64)a1, (__int64)v4, 0xBu, ArrayLength, ByteArrayElements);
  _JNIEnv::ReleaseByteArrayElements((__int64)a1, a3, ByteArrayElements, 0);
  return v4;
}

//----- (0000000000004D9C) ----------------------------------------------------
__int64 __fastcall _JNIEnv::GetByteArrayElements(__int64 a1, __int64 a2, __int64 a3)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 1472LL))(a1, a2, a3);
}

//----- (0000000000004DD8) ----------------------------------------------------
__int64 __fastcall _JNIEnv::SetByteArrayRegion(__int64 a1, __int64 a2, unsigned int a3, unsigned int a4, __int64 a5)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, _QWORD, _QWORD, __int64))(*(_QWORD *)a1 + 1664LL))(
           a1,
           a2,
           a3,
           a4,
           a5);
}

//----- (0000000000004E24) ----------------------------------------------------
__int64 __fastcall _JNIEnv::ReleaseByteArrayElements(__int64 a1, __int64 a2, __int64 a3, unsigned int a4)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, __int64, _QWORD))(*(_QWORD *)a1 + 1536LL))(a1, a2, a3, a4);
}

//----- (0000000000004E68) ----------------------------------------------------
__int64 __fastcall _JNIEnv::GetStaticFieldID(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, __int64, __int64))(*(_QWORD *)a1 + 1152LL))(a1, a2, a3, a4);
}

//----- (0000000000004EAC) ----------------------------------------------------
__int64 __fastcall _JNIEnv::GetStaticIntField(__int64 a1, __int64 a2, __int64 a3)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, __int64))(*(_QWORD *)a1 + 1200LL))(a1, a2, a3);
}

//----- (0000000000004EE8) ----------------------------------------------------
__int64 __fastcall _JNIEnv::GetStaticMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  return (*(__int64 (__fastcall **)(__int64, __int64, __int64, __int64))(*(_QWORD *)a1 + 904LL))(a1, a2, a3, a4);
}

//----- (0000000000004F2C) ----------------------------------------------------
__int64 _JNIEnv::CallStaticObjectMethod(__int64 a1, __int64 a2, __int64 a3, ...)
{
  __int64 (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+E0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+108h] [xbp-28h] BYREF
  __int64 v7; // [xsp+128h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(__int64 (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 920LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (0000000000005028) ----------------------------------------------------
__int64 __fastcall _JNIEnv::GetObjectClass(__int64 a1, __int64 a2)
{
  return (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)a1 + 248LL))(a1, a2);
}

//----- (000000000000505C) ----------------------------------------------------
__int64 _JNIEnv::CallVoidMethod(__int64 a1, __int64 a2, __int64 a3, ...)
{
  __int64 (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+D0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+F8h] [xbp-28h] BYREF
  __int64 v7; // [xsp+118h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(__int64 (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 496LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (0000000000005148) ----------------------------------------------------
__int64 __fastcall _JNIEnv::GetArrayLength(__int64 a1, __int64 a2)
{
  return (*(__int64 (__fastcall **)(__int64, __int64))(*(_QWORD *)a1 + 1368LL))(a1, a2);
}

//----- (000000000000517C) ----------------------------------------------------
__int64 _JNIEnv::CallStaticBooleanMethod(__int64 a1, __int64 a2, __int64 a3, ...)
{
  unsigned __int8 (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+E0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+108h] [xbp-28h] BYREF
  __int64 v7; // [xsp+128h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(unsigned __int8 (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 944LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (0000000000005278) ----------------------------------------------------
__int64 _JNIEnv::CallStaticLongMethod(__int64 a1, __int64 a2, __int64 a3, ...)
{
  __int64 (__fastcall *v3)(__int64, __int64, __int64, __va_list_tag *); // x8
  gcc_va_list va1; // [xsp+E0h] [xbp-50h] BYREF
  gcc_va_list va; // [xsp+108h] [xbp-28h] BYREF
  __int64 v7; // [xsp+128h] [xbp-8h]

  va_start(va, a3);
  v7 = *(_QWORD *)(_ReadStatusReg(TPIDR_EL0) + 40);
  v3 = *(__int64 (__fastcall **)(__int64, __int64, __int64, __va_list_tag *))(*(_QWORD *)a1 + 1064LL);
  va_copy(va1, va);
  return v3(a1, a2, a3, va1);
}

//----- (0000000000005380) ----------------------------------------------------
void sub_5380()
{
  JUMPOUT(0);
}
// 5390: control flows out of bounds to 0

//----- (00000000000053C0) ----------------------------------------------------
// attributes: thunk
jbyteArray __fastcall _JNIEnv::NewByteArray(_JNIEnv *this, unsigned int a2)
{
  return _ZN7_JNIEnv12NewByteArrayEi(this, a2);
}

//----- (00000000000053D0) ----------------------------------------------------
// attributes: thunk
jbyteArray __fastcall melon4Key(_JNIEnv *a1)
{
  return _Z9melon4KeyP7_JNIEnvP8_jobject(a1);
}

//----- (00000000000053E0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall sha256(_JNIEnv *a1)
{
  return _Z6sha256P7_JNIEnvP8_jobjectP11_jbyteArray(a1);
}

//----- (00000000000053F0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall aes256(_JNIEnv *a1, __int64 a2, int a3)
{
  return _Z6aes256P7_JNIEnvP8_jobjectiP11_jbyteArrayS4_S4_(a1, a2, a3);
}

//----- (0000000000005400) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::DeleteLocalRef(__int64 a1, __int64 a2)
{
  return _ZN7_JNIEnv14DeleteLocalRefEP8_jobject(a1, a2);
}

//----- (0000000000005410) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::SetByteArrayRegion(__int64 a1, __int64 a2, unsigned int a3, unsigned int a4, __int64 a5)
{
  return _ZN7_JNIEnv18SetByteArrayRegionEP11_jbyteArrayiiPKa(a1, a2, a3, a4, a5);
}

//----- (0000000000005420) ----------------------------------------------------
// attributes: thunk
jclass __fastcall _JNIEnv::FindClass(_JNIEnv *this, const char *a2)
{
  return _ZN7_JNIEnv9FindClassEPKc(this, a2);
}

//----- (0000000000005430) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::GetStaticMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  return _ZN7_JNIEnv17GetStaticMethodIDEP7_jclassPKcS3_(a1, a2, a3, a4);
}

//----- (0000000000005440) ----------------------------------------------------
// attributes: thunk
jstring __fastcall _JNIEnv::NewStringUTF(_JNIEnv *this, const char *a2)
{
  return _ZN7_JNIEnv12NewStringUTFEPKc(this, a2);
}

//----- (0000000000005450) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::CallStaticObjectMethod(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv22CallStaticObjectMethodEP7_jclassP10_jmethodIDz(a1, a2, a3);
}

//----- (0000000000005460) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::GetObjectClass(__int64 a1, __int64 a2)
{
  return _ZN7_JNIEnv14GetObjectClassEP8_jobject(a1, a2);
}

//----- (0000000000005470) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::GetMethodID(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  return _ZN7_JNIEnv11GetMethodIDEP7_jclassPKcS3_(a1, a2, a3, a4);
}

//----- (0000000000005480) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::CallVoidMethod(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv14CallVoidMethodEP8_jobjectP10_jmethodIDz(a1, a2, a3);
}

//----- (0000000000005490) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::CallObjectMethod(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv16CallObjectMethodEP8_jobjectP10_jmethodIDz(a1, a2, a3);
}

//----- (00000000000054A0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::NewObject(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv9NewObjectEP7_jclassP10_jmethodIDz(a1, a2, a3);
}

//----- (00000000000054B0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::GetStaticFieldID(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  return _ZN7_JNIEnv16GetStaticFieldIDEP7_jclassPKcS3_(a1, a2, a3, a4);
}

//----- (00000000000054C0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::GetStaticIntField(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv17GetStaticIntFieldEP7_jclassP9_jfieldID(a1, a2, a3);
}

//----- (00000000000054D0) ----------------------------------------------------
// attributes: thunk
jbyteArray __fastcall shuffle4Key(_JNIEnv *a1, __int64 a2, __int64 a3, __int64 a4)
{
  return _Z11shuffle4KeyP7_JNIEnvP8_jobjectP11_jbyteArrayS4_(a1, a2, a3, a4);
}

//----- (00000000000054E0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::GetArrayLength(__int64 a1, __int64 a2)
{
  return _ZN7_JNIEnv14GetArrayLengthEP7_jarray(a1, a2);
}

//----- (00000000000054F0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::GetByteArrayElements(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv20GetByteArrayElementsEP11_jbyteArrayPh(a1, a2, a3);
}

//----- (0000000000005500) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::ReleaseByteArrayElements(__int64 a1, __int64 a2, __int64 a3, unsigned int a4)
{
  return _ZN7_JNIEnv24ReleaseByteArrayElementsEP11_jbyteArrayPai(a1, a2, a3, a4);
}

//----- (0000000000005510) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall melonCrypto(_JNIEnv *a1, __int64 a2, int a3, __int64 a4, __int64 a5)
{
  return _Z11melonCryptoP7_JNIEnvP8_jobjectiP11_jbyteArrayS4_S4_(a1, a2, a3, a4, a5);
}

//----- (0000000000005520) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall byteArray2String(_JNIEnv *a1)
{
  return _Z16byteArray2StringP7_JNIEnvP8_jobjectP11_jbyteArray(a1);
}

//----- (0000000000005530) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::CallBooleanMethod(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv17CallBooleanMethodEP8_jobjectP10_jmethodIDz(a1, a2, a3);
}

//----- (0000000000005540) ----------------------------------------------------
// attributes: thunk
jbyteArray __fastcall premium4Key(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  return _Z11premium4KeyP7_JNIEnvP8_jobjectP11_jbyteArray(a1, a2, a3);
}

//----- (0000000000005560) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::CallIntMethod(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv13CallIntMethodEP8_jobjectP10_jmethodIDz(a1, a2, a3);
}

//----- (0000000000005570) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall currentTimeMillis(_JNIEnv *a1)
{
  return _Z17currentTimeMillisP7_JNIEnvP8_jobject(a1);
}

//----- (0000000000005580) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall convertString2Long(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  return _Z18convertString2LongP7_JNIEnvP8_jobjectP8_jstring(a1, a2, a3);
}

//----- (0000000000005590) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall equalsText(_JNIEnv *a1)
{
  return _Z10equalsTextP7_JNIEnvP8_jobjectP8_jstringS4_(a1);
}

//----- (00000000000055A0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::CallStaticLongMethod(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv20CallStaticLongMethodEP7_jclassP10_jmethodIDz(a1, a2, a3);
}

//----- (00000000000055B0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall _JNIEnv::CallStaticBooleanMethod(__int64 a1, __int64 a2, __int64 a3)
{
  return _ZN7_JNIEnv23CallStaticBooleanMethodEP7_jclassP10_jmethodIDz(a1, a2, a3);
}

//----- (00000000000055C0) ----------------------------------------------------
// attributes: thunk
__int64 __fastcall string2ByteArray(_JNIEnv *a1, __int64 a2, __int64 a3)
{
  return _Z16string2ByteArrayP7_JNIEnvP8_jobjectP8_jstring(a1, a2, a3);
}

// nfuncs=90 queued=84 decompiled=84 lumina nreq=0 worse=0 better=0
// ALL OK, 84 function(s) have been successfully decompiled
