package com.airbnb.lottie;

import android.graphics.Bitmap.Config;
import android.graphics.Bitmap;
import android.graphics.ColorFilter;
import android.graphics.Path;
import android.graphics.PointF;
import android.graphics.Typeface;
import com.airbnb.lottie.value.ScaleXY;

public interface LottieProperty {
    public static final Float BLUR_RADIUS;
    public static final Integer COLOR;
    public static final ColorFilter COLOR_FILTER;
    public static final Float CORNER_RADIUS;
    public static final Integer DROP_SHADOW_COLOR;
    public static final Float DROP_SHADOW_DIRECTION;
    public static final Float DROP_SHADOW_DISTANCE;
    public static final Float DROP_SHADOW_OPACITY;
    public static final Float DROP_SHADOW_RADIUS;
    public static final PointF ELLIPSE_SIZE;
    public static final Integer[] GRADIENT_COLOR;
    public static final Bitmap IMAGE;
    public static final Integer OPACITY;
    public static final Path PATH;
    public static final Float POLYSTAR_INNER_RADIUS;
    public static final Float POLYSTAR_INNER_ROUNDEDNESS;
    public static final Float POLYSTAR_OUTER_RADIUS;
    public static final Float POLYSTAR_OUTER_ROUNDEDNESS;
    public static final Float POLYSTAR_POINTS;
    public static final Float POLYSTAR_ROTATION;
    public static final PointF POSITION;
    public static final PointF RECTANGLE_SIZE;
    public static final Float REPEATER_COPIES;
    public static final Float REPEATER_OFFSET;
    public static final Integer STROKE_COLOR;
    public static final Float STROKE_WIDTH;
    public static final CharSequence TEXT;
    public static final Float TEXT_SIZE;
    public static final Float TEXT_TRACKING;
    public static final Float TIME_REMAP;
    public static final PointF TRANSFORM_ANCHOR_POINT;
    public static final Float TRANSFORM_END_OPACITY;
    public static final Integer TRANSFORM_OPACITY;
    public static final PointF TRANSFORM_POSITION;
    public static final Float TRANSFORM_POSITION_X;
    public static final Float TRANSFORM_POSITION_Y;
    public static final Float TRANSFORM_ROTATION;
    public static final ScaleXY TRANSFORM_SCALE;
    public static final Float TRANSFORM_SKEW;
    public static final Float TRANSFORM_SKEW_ANGLE;
    public static final Float TRANSFORM_START_OPACITY;
    public static final Typeface TYPEFACE;

    static {
        LottieProperty.COLOR = 1;
        LottieProperty.STROKE_COLOR = 2;
        LottieProperty.TRANSFORM_OPACITY = 3;
        LottieProperty.OPACITY = 4;
        LottieProperty.DROP_SHADOW_COLOR = 5;
        LottieProperty.TRANSFORM_ANCHOR_POINT = new PointF();
        LottieProperty.TRANSFORM_POSITION = new PointF();
        LottieProperty.TRANSFORM_POSITION_X = 15.0f;
        LottieProperty.TRANSFORM_POSITION_Y = 16.0f;
        LottieProperty.BLUR_RADIUS = 17.0f;
        LottieProperty.ELLIPSE_SIZE = new PointF();
        LottieProperty.RECTANGLE_SIZE = new PointF();
        LottieProperty.CORNER_RADIUS = 0.0f;
        LottieProperty.POSITION = new PointF();
        LottieProperty.TRANSFORM_SCALE = new ScaleXY();
        LottieProperty.TRANSFORM_ROTATION = 1.0f;
        LottieProperty.TRANSFORM_SKEW = 0.0f;
        LottieProperty.TRANSFORM_SKEW_ANGLE = 0.0f;
        LottieProperty.STROKE_WIDTH = 2.0f;
        LottieProperty.TEXT_TRACKING = 3.0f;
        LottieProperty.REPEATER_COPIES = 4.0f;
        LottieProperty.REPEATER_OFFSET = 5.0f;
        LottieProperty.POLYSTAR_POINTS = 6.0f;
        LottieProperty.POLYSTAR_ROTATION = 7.0f;
        LottieProperty.POLYSTAR_INNER_RADIUS = 8.0f;
        LottieProperty.POLYSTAR_OUTER_RADIUS = 9.0f;
        LottieProperty.POLYSTAR_INNER_ROUNDEDNESS = 10.0f;
        LottieProperty.POLYSTAR_OUTER_ROUNDEDNESS = 11.0f;
        LottieProperty.TRANSFORM_START_OPACITY = 12.0f;
        LottieProperty.TRANSFORM_END_OPACITY = 12.1f;
        LottieProperty.TIME_REMAP = 13.0f;
        LottieProperty.TEXT_SIZE = 14.0f;
        LottieProperty.DROP_SHADOW_OPACITY = 15.0f;
        LottieProperty.DROP_SHADOW_DIRECTION = 16.0f;
        LottieProperty.DROP_SHADOW_DISTANCE = 17.0f;
        LottieProperty.DROP_SHADOW_RADIUS = 18.0f;
        LottieProperty.COLOR_FILTER = new ColorFilter();
        LottieProperty.GRADIENT_COLOR = new Integer[0];
        LottieProperty.TYPEFACE = Typeface.DEFAULT;
        LottieProperty.IMAGE = Bitmap.createBitmap(1, 1, Bitmap.Config.ALPHA_8);
        LottieProperty.TEXT = "dynamic_text";
        LottieProperty.PATH = new Path();
    }
}

