package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.PendingResult.StatusListener;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.TransformedResult;
import com.google.android.gms.common.internal.Preconditions;
import com.google.android.gms.common.internal.ShowFirstParty;
import java.util.concurrent.TimeUnit;

public final class zacp extends PendingResult {
    private final Status zaa;

    public zacp(Status status0) {
        Preconditions.checkNotNull(status0, "Status must not be null");
        Preconditions.checkArgument(!status0.isSuccess(), "Status must not be success");
        this.zaa = status0;
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    public final void addStatusListener(StatusListener pendingResult$StatusListener0) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    public final Result await() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    public final Result await(long v, TimeUnit timeUnit0) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    public final void cancel() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    public final boolean isCanceled() {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    public final void setResultCallback(ResultCallback resultCallback0) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    public final void setResultCallback(ResultCallback resultCallback0, long v, TimeUnit timeUnit0) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    @Override  // com.google.android.gms.common.api.PendingResult
    @ShowFirstParty
    public final TransformedResult then(ResultTransform resultTransform0) {
        throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    }

    public final Status zaa() {
        return this.zaa;
    }
}

